(** EquivCheck.v Autogenerated by REM-verification **)
Require Import Primitives.
Import Primitives.
Require Import BusinessLogic.
Require Import BusinessLogicRefactored.
Local Open Scope Primitives_scope.


Lemma example9_pricing_compute_total_price_cents_equiv_check : forall (item : example9_pricing_Item_t) (discount_percent : u32) (region : example9_pricing_Region_t),
    BusinessLogic.example9_pricing_compute_total_price_cents item discount_percent region = BusinessLogicRefactored.example9_pricing_compute_total_price_cents item discount_percent region.
Proof.
    intros item discount_percent region.
    unfold BusinessLogic.example9_pricing_compute_total_price_cents.
    unfold BusinessLogicRefactored.example9_pricing_compute_total_price_cents.
    reflexivity.
Qed.
