(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [extract_from_nested] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Input.

(** [extract_from_nested::main]:
    Source: 'src/main.rs', lines 1:0-7:1 *)
Definition main : result unit :=
  _ <- i32_add 2%i32 2%i32; Ok tt.

End Input.
