(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [never] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Never.

(** [core::fmt::Arguments]
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 618:0-618:24
    Name pattern: [core::fmt::Arguments] *)
Axiom core_fmt_Arguments_t : Type.

(** [core::fmt::rt::{core::fmt::Arguments<'a>}::new_const]:
    Source: '/rustc/library/core/src/fmt/rt.rs', lines 194:4-194:81
    Name pattern: [core::fmt::rt::{core::fmt::Arguments<''a>}::new_const] *)
Axiom core_fmt_rt_Arguments_new_const :
  forall{N : usize}, array str N -> result core_fmt_Arguments_t
.

(** [never::crash]:
    Source: 'src/main.rs', lines 5:0-5:36 *)
Definition crash : result unit :=
  admit.

(** [never::main]:
    Source: 'src/main.rs', lines 1:0-3:1 *)
Definition main : result unit :=
  crash.

End Never.
