(** EquivCheck.v Autogenerated by REM-verification **)
Require Import Primitives.
Import Primitives.
Require Import BusinessLogic.
Require Import BusinessLogicRefactored.
Local Open Scope Primitives_scope.


Lemma example4_order_apply_event_equiv_check : forall (state : example4_order_OrderState_t) (event : example4_order_Event_t),
    BusinessLogic.example4_order_apply_event state event = BusinessLogicRefactored.example4_order_apply_event state event.
Proof.
    intros state event.
    unfold BusinessLogic.example4_order_apply_event.
    unfold BusinessLogicRefactored.example4_order_apply_event.
    reflexivity.
Qed.
