(** EquivCheck.v Autogenerated by REM-verification **)
Require Import Primitives.
Import Primitives.
Require Import BusinessLogic.
Require Import BusinessLogicRefactored.
Local Open Scope Primitives_scope.


Lemma example6_grading_compute_final_mark_equiv_check : forall (c : example6_grading_Components_t),
    BusinessLogic.example6_grading_compute_final_mark c = BusinessLogicRefactored.example6_grading_compute_final_mark c.
Proof.
    intros c.
    unfold BusinessLogic.example6_grading_compute_final_mark.
    unfold BusinessLogicRefactored.example6_grading_compute_final_mark.
    reflexivity.
Qed.
