(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [output] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Out.

(** Trait declaration: [core::convert::Into]
    Source: '/rustc/library/core/src/convert/mod.rs', lines 451:0-451:30
    Name pattern: [core::convert::Into] *)
Record core_convert_Into_t (Self : Type) (T : Type) := mkcore_convert_Into_t {
  core_convert_Into_t_into : Self -> result T;
}.

Arguments mkcore_convert_Into_t { _ } { _ }.
Arguments core_convert_Into_t_into { _ } { _ } _.

(** [output::Struct]
    Source: 'src/main.rs', lines 1:0-3:17 *)
Definition Struct_t {T : Type} (coreconvertIntoTI32Inst : core_convert_Into_t T
  i32) : Type :=
T
.

(** [output::fun_name]:
    Source: 'src/main.rs', lines 17:0-23:1 *)
Definition fun_name
  {T : Type} {V : Type} (coreconvertIntoTI32Inst : core_convert_Into_t T i32)
  (coremarkerCopyInst : core_marker_Copy T) (coreconvertIntoVI32Inst :
  core_convert_Into_t V i32) (t : T) (v : V) :
  result i32
  :=
  i <- coreconvertIntoTI32Inst.(core_convert_Into_t_into) t;
  i1 <- coreconvertIntoVI32Inst.(core_convert_Into_t_into) v;
  i32_add i i1
.

(** [output::{output::Struct<T>[TraitClause@1]}::func]:
    Source: 'src/main.rs', lines 8:4-14:5 *)
Definition struct_func
  {T : Type} {V : Type} (coreconvertIntoTI32Inst : core_convert_Into_t T i32)
  (coremarkerCopyInst : core_marker_Copy T) (coreconvertIntoVI32Inst :
  core_convert_Into_t V i32) (self : Struct_t T coreconvertIntoTI32Inst)
  (v : V) :
  result i32
  :=
  fun_name coreconvertIntoTI32Inst coremarkerCopyInst coreconvertIntoVI32Inst
    self v
.

(** [output::main]:
    Source: 'src/main.rs', lines 25:0-25:12 *)
Definition main : result unit :=
  Ok tt.

End Out.
