(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [bad] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Bad.

(** [bad::mutate_x]:
    Source: 'src/main.rs', lines 7:0-9:1 *)
Definition mutate_x (x : i32) : result unit :=
  Ok tt.

(** [bad::main]:
    Source: 'src/main.rs', lines 1:0-5:1 *)
Definition main : result unit :=
  let i := core_clone_impls_CloneI32_clone 0%i32 in
  _ <- mutate_x i;
  massert (0%i32 s= 3%i32)
.

End Bad.
