(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [good] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Good.

(** [good::mutate_x]:
    Source: 'src/main.rs', lines 7:0-9:1 *)
Definition mutate_x (x : i32) : result i32 :=
  Ok 3%i32.

(** [good::main]:
    Source: 'src/main.rs', lines 1:0-5:1 *)
Definition main : result unit :=
  x <- mutate_x 0%i32; massert (x s= 3%i32).

End Good.
