(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [copy_custom_used_after] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Input.

(** [copy_custom_used_after::Counter]
    Source: 'src/main.rs', lines 2:0-2:20 *)
Definition Counter_t : Type := i32.

(** [copy_custom_used_after::{core::clone::Clone for copy_custom_used_after::Counter}::clone]:
    Source: 'src/main.rs', lines 1:9-1:14 *)
Definition clonecopy_custom_used_afterCounter_clone
  (self : Counter_t) : result Counter_t :=
  Ok self
.

(** Trait implementation: [copy_custom_used_after::{core::clone::Clone for copy_custom_used_after::Counter}]
    Source: 'src/main.rs', lines 1:9-1:14 *)
Definition core_clone_Clonecopy_custom_used_afterCounter : core_clone_Clone
  Counter_t := {|
  core_clone_Clone_clone := clonecopy_custom_used_afterCounter_clone;
|}.

(** Trait implementation: [copy_custom_used_after::{core::marker::Copy for copy_custom_used_after::Counter}]
    Source: 'src/main.rs', lines 1:16-1:20 *)
Definition core_marker_Copycopy_custom_used_afterCounter : core_marker_Copy
  Counter_t := {|
  cloneInst := core_clone_Clonecopy_custom_used_afterCounter;
|}.

(** [copy_custom_used_after::foo]:
    Source: 'src/main.rs', lines 3:0-7:1 *)
Definition foo : result unit :=
  Ok tt.

(** [copy_custom_used_after::main]:
    Source: 'src/main.rs', lines 9:0-11:1 *)
Definition main : result unit :=
  Ok tt.

End Input.
