(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [output] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Out.

(** [output::Counter]
    Source: 'src/main.rs', lines 2:0-2:20 *)
Definition Counter_t : Type := i32.

(** [output::{core::clone::Clone for output::Counter}::clone]:
    Source: 'src/main.rs', lines 1:9-1:14 *)
Definition cloneoutputCounter_clone (self : Counter_t) : result Counter_t :=
  Ok self
.

(** Trait implementation: [output::{core::clone::Clone for output::Counter}]
    Source: 'src/main.rs', lines 1:9-1:14 *)
Definition core_clone_CloneoutputCounter : core_clone_Clone Counter_t := {|
  core_clone_Clone_clone := cloneoutputCounter_clone;
|}.

(** Trait implementation: [output::{core::marker::Copy for output::Counter}]
    Source: 'src/main.rs', lines 1:16-1:20 *)
Definition core_marker_CopyoutputCounter : core_marker_Copy Counter_t := {|
  cloneInst := core_clone_CloneoutputCounter;
|}.

(** [output::fun_name]:
    Source: 'src/main.rs', lines 9:0-11:1 *)
Definition fun_name (c : Counter_t) : result unit :=
  Ok tt.

(** [output::foo]:
    Source: 'src/main.rs', lines 3:0-7:1 *)
Definition foo : result unit :=
  fun_name 0%i32.

(** [output::main]:
    Source: 'src/main.rs', lines 13:0-13:12 *)
Definition main : result unit :=
  Ok tt.

End Out.
