(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [extract_cast] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Input.

(** [extract_cast::Counter]
    Source: 'src/main.rs', lines 1:0-1:33 *)
Record Counter_t := mkCounter_t { counter_n : i32; counter_m : i32; }.

(** [extract_cast::foo]:
    Source: 'src/main.rs', lines 2:0-5:1 *)
Definition foo : result unit :=
  _ <- i32_add 1%i32 2%i32; Ok tt.

(** [extract_cast::main]:
    Source: 'src/main.rs', lines 7:0-9:1 *)
Definition main : result unit :=
  Ok tt.

End Input.
