(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [output] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Out.

(** [output::Counter]
    Source: 'src/main.rs', lines 1:0-4:1 *)
Record Counter_t := mkCounter_t { counter_n : i32; counter_m : i32; }.

(** [output::fun_name]:
    Source: 'src/main.rs', lines 10:0-12:1 *)
Definition fun_name : result (i32 * i32) :=
  Ok (1%i32, 2%i32).

(** [output::foo]:
    Source: 'src/main.rs', lines 5:0-8:1 *)
Definition foo : result unit :=
  p <- fun_name; let (n, k) := p in _ <- i32_add n k; Ok tt
.

(** [output::main]:
    Source: 'src/main.rs', lines 14:0-14:12 *)
Definition main : result unit :=
  Ok tt.

End Out.
