(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [argument_and_locals] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Input.

(** [argument_and_locals::foo]:
    Source: 'src/main.rs', lines 1:0-5:1 *)
Definition foo : result u32 :=
  u32_add 2%u32 1%u32.

(** [argument_and_locals::main]:
    Source: 'src/main.rs', lines 7:0-9:1 *)
Definition main : result unit :=
  Ok tt.

End Input.
