(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [output] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Out.

(** [output::fun_name]:
    Source: 'src/main.rs', lines 6:0-9:1 *)
Definition fun_name (n : u32) : result u32 :=
  u32_add n 1%u32.

(** [output::foo]:
    Source: 'src/main.rs', lines 1:0-4:1 *)
Definition foo : result u32 :=
  fun_name 2%u32.

(** [output::main]:
    Source: 'src/main.rs', lines 11:0-11:12 *)
Definition main : result unit :=
  Ok tt.

End Out.
