(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [return_to_parent] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Input.

(** [return_to_parent::foo]:
    Source: 'src/main.rs', lines 1:0-7:1 *)
Definition foo : result i64 :=
  _ <- i32_add 1%i32 1%i32; Ok 1%i64.

(** [return_to_parent::main]:
    Source: 'src/main.rs', lines 9:0-11:1 *)
Definition main : result unit :=
  Ok tt.

End Input.
