(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [output] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Out.

(** [core::result::Result]
    Source: '/rustc/library/core/src/result.rs', lines 557:0-557:21
    Name pattern: [core::result::Result] *)
Inductive core_result_Result_t (T : Type) (E : Type) :=
| Core_result_Result_Ok : T -> core_result_Result_t T E
| Core_result_Result_Err : E -> core_result_Result_t T E
.

Arguments Core_result_Result_Ok { _ } { _ }.
Arguments Core_result_Result_Err { _ } { _ }.

(** [output::fun_name]:
    Source: 'src/main.rs', lines 10:0-15:1 *)
Definition fun_name (n : i32) : result (core_result_Result_t i32 i64) :=
  _ <- i32_add n 1%i32; Ok (Core_result_Result_Err 1%i64)
.

(** [output::foo]:
    Source: 'src/main.rs', lines 1:0-8:1 *)
Definition foo : result i64 :=
  r <- fun_name 1%i32;
  match r with
  | Core_result_Result_Ok value =>
    i <- i32_add 1%i32 value; scalar_cast I32 I64 i
  | Core_result_Result_Err value => Ok value
  end
.

(** [output::main]:
    Source: 'src/main.rs', lines 17:0-17:12 *)
Definition main : result unit :=
  Ok tt.

End Out.
