(** EquivCheck.v Autogenerated by REM-verification **)
Require Import Primitives.
Import Primitives.
Require Import BusinessLogic.
Require Import BusinessLogicRefactored.
Local Open Scope Primitives_scope.


Lemma example8_intervals_merge_intervals_equiv_check : forall (a : example8_intervals_Interval_t) (b : example8_intervals_Interval_t),
    BusinessLogic.example8_intervals_merge_intervals a b = BusinessLogicRefactored.example8_intervals_merge_intervals a b.
Proof.
    intros a b.
    unfold BusinessLogic.example8_intervals_merge_intervals.
    unfold BusinessLogicRefactored.example8_intervals_merge_intervals.
    reflexivity.
Qed.
