(** EquivCheck.v Autogenerated by REM-verification **)
Require Import Primitives.
Import Primitives.
Require Import BusinessLogic.
Require Import BusinessLogicRefactored.
Local Open Scope Primitives_scope.


