(** EquivCheck.v Autogenerated by REM-verification **)
Require Import Primitives.
Import Primitives.
Require Import Input.
Require Import Out.
Local Open Scope Primitives_scope.


Lemma main_equiv_check :
    Input.main = Out.main.
Proof.
    intros.
    unfold Input.main.
    unfold Out.main.
    reflexivity.
Qed.
