(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [break_stmt] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Input.

(** [break_stmt::main]:
    Source: 'src/main.rs', lines 1:0-5:1 *)
Definition main : result unit :=
  _ <- i32_add 2%i32 2%i32; Ok tt.

End Input.
