(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [output] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Out.

(** [output::fun_name]:
    Source: 'src/main.rs', lines 7:0-9:1 *)
Definition fun_name : result i32 :=
  i32_add 2%i32 2%i32.

(** [output::main]:
    Source: 'src/main.rs', lines 1:0-5:1 *)
Definition main : result unit :=
  _ <- fun_name; Ok tt.

End Out.
