(** EquivCheck.v Autogenerated by REM-verification **)
Require Import Primitives.
Import Primitives.
Require Import BusinessLogic.
Require Import BusinessLogicRefactored.
Local Open Scope Primitives_scope.


Lemma example1_loyalty_update_customer_tier_equiv_check : forall (c : example1_loyalty_Customer_t),
    BusinessLogic.example1_loyalty_update_customer_tier c = BusinessLogicRefactored.example1_loyalty_update_customer_tier c.
Proof.
    intros c.
    unfold BusinessLogic.example1_loyalty_update_customer_tier.
    unfold BusinessLogicRefactored.example1_loyalty_update_customer_tier.
    reflexivity.
Qed.

Print BusinessLogic.example1_loyalty_update_customer_tier.
Print BusinessLogic.example1_loyalty_compute_tier.