(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [orig] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Orig.

(** [orig::main]:
    Source: 'src/main.rs', lines 1:0-5:1 *)
Definition main : result unit :=
  massert (3%i32 s= 3%i32).

End Orig.
