name: Compile and Push LaTeX Document
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'
      - '**/.gitignore'
      - '**/.gitattributes'
      - '**/Makefile'
      - 'Assets/**'
      - 'main.pdf'
  pull_request:
    paths-ignore:
        - '**/README.md'
        - '**/LICENSE'
        - '**/.gitignore'
        - '**/.gitattributes'
        - '**/Makefile'
        - 'Assets/**'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: LaTeX Document Compilation
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          
      - name: Commit PDF File
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Auto-update compiled report"
          add: "main.pdf"