[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
glib = "0.20.0"
# gdk = "0.18.0"
gtk = { version = "0.9.0", package = "gtk4", features = ["v4_12"] }
gio = "0.20.0"
solar_array = { path = "../solar_array" }
vehicle_stability = { path = "../vehicle_stability" }