(** EquivCheck.v Autogenerated by REM-verification **)
Require Import Primitives.
Import Primitives.
Require Import BusinessLogic.
Require Import BusinessLogicRefactored.
Local Open Scope Primitives_scope.


Lemma example3_inventory_apply_stock_change_equiv_check : forall (item : example3_inventory_Item_t) (delta : i32),
    BusinessLogic.example3_inventory_apply_stock_change item delta = BusinessLogicRefactored.example3_inventory_apply_stock_change item delta.
Proof.
    intros item delta.
    unfold BusinessLogic.example3_inventory_apply_stock_change.
    unfold BusinessLogicRefactored.example3_inventory_apply_stock_change.
    reflexivity.
Qed.
