(** EquivCheck.v Autogenerated by REM-verification **)
Require Import Primitives.
Import Primitives.
Require Import Orig.
Require Import Good.
Local Open Scope Primitives_scope.


Lemma main_equiv_check :
    Orig.main = Good.main.
    Proof.
    intros.
    unfold Orig.main.
    unfold Good.main.
    reflexivity.
    Qed.
