(** EquivCheck.v Autogenerated by REM-verification **)
Require Import Primitives.
Import Primitives.
Require Import Orig.
Require Import Bad.
Local Open Scope Primitives_scope.


Lemma main_equiv_check :
Orig.main = Bad.main.
Proof.
intros.
unfold Orig.main.
unfold Bad.main.
reflexivity.
Qed.
