(** EquivCheck.v Autogenerated by REM-verification **)
Require Import Primitives.
Import Primitives.
Require Import BusinessLogic.
Require Import BusinessLogicRefactored.
Local Open Scope Primitives_scope.


Lemma example2_transfer_transfer_equiv_check : forall (src : example2_transfer_Account_t) (dst : example2_transfer_Account_t) (amount_cents : i64),
    BusinessLogic.example2_transfer_transfer src dst amount_cents = BusinessLogicRefactored.example2_transfer_transfer src dst amount_cents.
Proof.
    intros src dst amount_cents.
    unfold BusinessLogic.example2_transfer_transfer.
    unfold BusinessLogicRefactored.example2_transfer_transfer.
    reflexivity.
Qed.
