(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [mut_method_call] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Input.

(** Trait declaration: [mut_method_call::I]
    Source: 'src/main.rs', lines 1:0-3:1 *)
Record I_t (Self : Type) := mkI_t { I_t_inc : Self -> result Self; }.

Arguments mkI_t { _ }.
Arguments I_t_inc { _ } _.

(** [mut_method_call::{mut_method_call::I for i32}::inc]:
    Source: 'src/main.rs', lines 5:4-5:36 *)
Definition iI32_inc (self : i32) : result i32 :=
  i32_add self 1%i32.

(** Trait implementation: [mut_method_call::{mut_method_call::I for i32}]
    Source: 'src/main.rs', lines 4:0-6:1 *)
Definition II32 : I_t i32 := {| I_t_inc := iI32_inc; |}.

(** [mut_method_call::foo]:
    Source: 'src/main.rs', lines 7:0-10:1 *)
Definition foo : result unit :=
  _ <- iI32_inc 1%i32; Ok tt.

(** [mut_method_call::main]:
    Source: 'src/main.rs', lines 12:0-14:1 *)
Definition main : result unit :=
  Ok tt.

End Input.
