(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [output] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Out.

(** Trait declaration: [output::I]
    Source: 'src/main.rs', lines 1:0-3:1 *)
Record I_t (Self : Type) := mkI_t { I_t_inc : Self -> result Self; }.

Arguments mkI_t { _ }.
Arguments I_t_inc { _ } _.

(** [output::{output::I for i32}::inc]:
    Source: 'src/main.rs', lines 5:4-7:5 *)
Definition iI32_inc (self : i32) : result i32 :=
  i32_add self 1%i32.

(** Trait implementation: [output::{output::I for i32}]
    Source: 'src/main.rs', lines 4:0-8:1 *)
Definition II32 : I_t i32 := {| I_t_inc := iI32_inc; |}.

(** [output::fun_name]:
    Source: 'src/main.rs', lines 14:0-16:1 *)
Definition fun_name (n : i32) : result unit :=
  _ <- iI32_inc n; Ok tt.

(** [output::foo]:
    Source: 'src/main.rs', lines 9:0-12:1 *)
Definition foo : result unit :=
  fun_name 1%i32.

(** [output::main]:
    Source: 'src/main.rs', lines 18:0-18:12 *)
Definition main : result unit :=
  Ok tt.

End Out.
