(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [extract_partial_block] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Input.

(** [extract_partial_block::foo]:
    Source: 'src/main.rs', lines 1:0-8:1 *)
Definition foo : result unit :=
  v <- i32_mul 2%i32 1%i32;
  _ <- i32_add v 1%i32;
  _ <- i32_add 3%i32 1%i32;
  Ok tt
.

(** [extract_partial_block::main]:
    Source: 'src/main.rs', lines 10:0-12:1 *)
Definition main : result unit :=
  Ok tt.

End Input.
