(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [output] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Out.

(** [output::fun_name]:
    Source: 'src/main.rs', lines 9:0-13:1 *)
Definition fun_name (m : i32) (n : i32) : result (i32 * i32) :=
  v <- i32_mul m n; Ok (v, 3%i32)
.

(** [output::foo]:
    Source: 'src/main.rs', lines 1:0-7:1 *)
Definition foo : result unit :=
  p <- fun_name 2%i32 1%i32;
  let (v, w) := p in
  _ <- i32_add v 1%i32;
  _ <- i32_add w 1%i32;
  Ok tt
.

(** [output::main]:
    Source: 'src/main.rs', lines 15:0-15:12 *)
Definition main : result unit :=
  Ok tt.

End Out.
