(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [business_logic] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module BusinessLogic.

(** Trait declaration: [core::cmp::PartialEq]
    Source: '/rustc/library/core/src/cmp.rs', lines 251:0-251:65
    Name pattern: [core::cmp::PartialEq] *)
Record core_cmp_PartialEq_t (Self : Type) (Rhs : Type)
  := mkcore_cmp_PartialEq_t {
  core_cmp_PartialEq_t_eq : Self -> Rhs -> result bool;
}.

Arguments mkcore_cmp_PartialEq_t { _ } { _ }.
Arguments core_cmp_PartialEq_t_eq { _ } { _ } _.

(** Trait declaration: [core::cmp::Eq]
    Source: '/rustc/library/core/src/cmp.rs', lines 338:0-338:58
    Name pattern: [core::cmp::Eq] *)
Record core_cmp_Eq_t (Self : Type) := mkcore_cmp_Eq_t {
  core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst : core_cmp_PartialEq_t Self Self;
}.

Arguments mkcore_cmp_Eq_t { _ }.
Arguments core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst { _ } _.

(** [core::num::{u32}::saturating_add]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 2145:8-2145:60
    Name pattern: [core::num::{u32}::saturating_add] *)
Axiom core_num_U32_saturating_add : u32 -> u32 -> result u32.

(** [core::num::{u32}::saturating_mul]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 2234:8-2234:60
    Name pattern: [core::num::{u32}::saturating_mul] *)
Axiom core_num_U32_saturating_mul : u32 -> u32 -> result u32.

(** [business_logic::example10_retry::RetryConfig]
    Source: 'src/example10_retry.rs', lines 1:0-5:1 *)
Record example10_retry_RetryConfig_t :=
mkexample10_retry_RetryConfig_t {
  example10_retry_RetryConfig_max_attempts : u32;
  example10_retry_RetryConfig_initial_delay_ms : u32;
  example10_retry_RetryConfig_backoff_factor : u32;
}
.

(** [business_logic::example10_retry::compute_total_backoff]: loop 0:
    Source: 'src/example10_retry.rs', lines 16:4-20:5 *)
Fixpoint example10_retry_compute_total_backoff_loop
  (i : u32) (i1 : u32) (attempts : u32) (delay : u32) (total : u32) :
  result u32
  :=
  if attempts s< i
  then (
    total1 <- core_num_U32_saturating_add total delay;
    delay1 <- core_num_U32_saturating_mul delay i1;
    attempts1 <- u32_add attempts 1%u32;
    example10_retry_compute_total_backoff_loop i i1 attempts1 delay1 total1)
  else Ok total
.

(** [business_logic::example10_retry::compute_total_backoff]:
    Source: 'src/example10_retry.rs', lines 7:0-23:1 *)
Definition example10_retry_compute_total_backoff
  (cfg : example10_retry_RetryConfig_t) : result u32 :=
  if cfg.(example10_retry_RetryConfig_max_attempts) s= 0%u32
  then Ok 0%u32
  else
    example10_retry_compute_total_backoff_loop
      cfg.(example10_retry_RetryConfig_max_attempts)
      cfg.(example10_retry_RetryConfig_backoff_factor) 0%u32
      cfg.(example10_retry_RetryConfig_initial_delay_ms) 0%u32
.

(** [business_logic::example10_retry::run_example]:
    Source: 'src/example10_retry.rs', lines 25:0-35:1 *)
Definition example10_retry_run_example : result unit :=
  total <-
    example10_retry_compute_total_backoff
      {|
        example10_retry_RetryConfig_max_attempts := 3%u32;
        example10_retry_RetryConfig_initial_delay_ms := 100%u32;
        example10_retry_RetryConfig_backoff_factor := 2%u32
      |};
  massert (total s= 700%u32)
.

(** [business_logic::example1_loyalty::Tier]
    Source: 'src/example1_loyalty.rs', lines 2:0-7:1 *)
Inductive example1_loyalty_Tier_t :=
| Example1_loyalty_Tier_Bronze : example1_loyalty_Tier_t
| Example1_loyalty_Tier_Silver : example1_loyalty_Tier_t
| Example1_loyalty_Tier_Gold : example1_loyalty_Tier_t
| Example1_loyalty_Tier_Platinum : example1_loyalty_Tier_t
.

(** [business_logic::example1_loyalty::{core::clone::Clone for business_logic::example1_loyalty::Tier}::clone]:
    Source: 'src/example1_loyalty.rs', lines 1:9-1:14 *)
Definition example1_loyalty_Clonebusiness_logicexample1_loyaltyTier_clone
  (self : example1_loyalty_Tier_t) : result example1_loyalty_Tier_t :=
  Ok self
.

(** Trait implementation: [business_logic::example1_loyalty::{core::clone::Clone for business_logic::example1_loyalty::Tier}]
    Source: 'src/example1_loyalty.rs', lines 1:9-1:14 *)
Definition core_clone_Clonebusiness_logicexample1_loyaltyTier :
  core_clone_Clone example1_loyalty_Tier_t := {|
  core_clone_Clone_clone :=
    example1_loyalty_Clonebusiness_logicexample1_loyaltyTier_clone;
|}.

(** Trait implementation: [business_logic::example1_loyalty::{core::marker::Copy for business_logic::example1_loyalty::Tier}]
    Source: 'src/example1_loyalty.rs', lines 1:16-1:20 *)
Definition core_marker_Copybusiness_logicexample1_loyaltyTier :
  core_marker_Copy example1_loyalty_Tier_t := {|
  cloneInst := core_clone_Clonebusiness_logicexample1_loyaltyTier;
|}.

(** [business_logic::example1_loyalty::{core::cmp::PartialEq<business_logic::example1_loyalty::Tier> for business_logic::example1_loyalty::Tier}::eq]:
    Source: 'src/example1_loyalty.rs', lines 10:4-18:5 *)
Definition
  example1_loyalty_PartialEqbusiness_logicexample1_loyaltyTierbusiness_logicexample1_loyaltyTier_eq
  (self : example1_loyalty_Tier_t) (other : example1_loyalty_Tier_t) :
  result bool
  :=
  match self with
  | Example1_loyalty_Tier_Bronze =>
    match other with
    | Example1_loyalty_Tier_Bronze => Ok true
    | Example1_loyalty_Tier_Silver => Ok false
    | Example1_loyalty_Tier_Gold => Ok false
    | Example1_loyalty_Tier_Platinum => Ok false
    end
  | Example1_loyalty_Tier_Silver =>
    match other with
    | Example1_loyalty_Tier_Bronze => Ok false
    | Example1_loyalty_Tier_Silver => Ok true
    | Example1_loyalty_Tier_Gold => Ok false
    | Example1_loyalty_Tier_Platinum => Ok false
    end
  | Example1_loyalty_Tier_Gold =>
    match other with
    | Example1_loyalty_Tier_Bronze => Ok false
    | Example1_loyalty_Tier_Silver => Ok false
    | Example1_loyalty_Tier_Gold => Ok true
    | Example1_loyalty_Tier_Platinum => Ok false
    end
  | Example1_loyalty_Tier_Platinum =>
    match other with
    | Example1_loyalty_Tier_Bronze => Ok false
    | Example1_loyalty_Tier_Silver => Ok false
    | Example1_loyalty_Tier_Gold => Ok false
    | Example1_loyalty_Tier_Platinum => Ok true
    end
  end
.

(** Trait implementation: [business_logic::example1_loyalty::{core::cmp::PartialEq<business_logic::example1_loyalty::Tier> for business_logic::example1_loyalty::Tier}]
    Source: 'src/example1_loyalty.rs', lines 9:0-19:1 *)
Definition
  core_cmp_PartialEqbusiness_logicexample1_loyaltyTierbusiness_logicexample1_loyaltyTier
  : core_cmp_PartialEq_t example1_loyalty_Tier_t example1_loyalty_Tier_t := {|
  core_cmp_PartialEq_t_eq :=
    example1_loyalty_PartialEqbusiness_logicexample1_loyaltyTierbusiness_logicexample1_loyaltyTier_eq;
|}.

(** Trait implementation: [business_logic::example1_loyalty::{core::cmp::Eq for business_logic::example1_loyalty::Tier}]
    Source: 'src/example1_loyalty.rs', lines 21:0-21:30 *)
Definition core_cmp_Eqbusiness_logicexample1_loyaltyTier : core_cmp_Eq_t
  example1_loyalty_Tier_t := {|
  core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst :=
    core_cmp_PartialEqbusiness_logicexample1_loyaltyTierbusiness_logicexample1_loyaltyTier;
|}.

(** [business_logic::example1_loyalty::Customer]
    Source: 'src/example1_loyalty.rs', lines 23:0-26:1 *)
Record example1_loyalty_Customer_t :=
mkexample1_loyalty_Customer_t {
  example1_loyalty_Customer_points : u32;
  example1_loyalty_Customer_tier : example1_loyalty_Tier_t;
}
.

(** [business_logic::example1_loyalty::update_customer_tier]:
    Source: 'src/example1_loyalty.rs', lines 28:0-40:1 *)
Definition example1_loyalty_update_customer_tier
  (c : example1_loyalty_Customer_t) : result example1_loyalty_Customer_t :=
  if c.(example1_loyalty_Customer_points) s< 1000%u32
  then
    Ok
      {|
        example1_loyalty_Customer_points :=
          c.(example1_loyalty_Customer_points);
        example1_loyalty_Customer_tier := Example1_loyalty_Tier_Bronze
      |}
  else
    if c.(example1_loyalty_Customer_points) s< 5000%u32
    then
      Ok
        {|
          example1_loyalty_Customer_points :=
            c.(example1_loyalty_Customer_points);
          example1_loyalty_Customer_tier := Example1_loyalty_Tier_Silver
        |}
    else
      if c.(example1_loyalty_Customer_points) s< 10000%u32
      then
        Ok
          {|
            example1_loyalty_Customer_points :=
              c.(example1_loyalty_Customer_points);
            example1_loyalty_Customer_tier := Example1_loyalty_Tier_Gold
          |}
      else
        Ok
          {|
            example1_loyalty_Customer_points :=
              c.(example1_loyalty_Customer_points);
            example1_loyalty_Customer_tier := Example1_loyalty_Tier_Platinum
          |}
.

(** [business_logic::example1_loyalty::run_example]:
    Source: 'src/example1_loyalty.rs', lines 42:0-51:1 *)
Definition example1_loyalty_run_example : result unit :=
  c <-
    example1_loyalty_update_customer_tier
      {|
        example1_loyalty_Customer_points := 4200%u32;
        example1_loyalty_Customer_tier := Example1_loyalty_Tier_Bronze
      |};
  b <-
    example1_loyalty_PartialEqbusiness_logicexample1_loyaltyTierbusiness_logicexample1_loyaltyTier_eq
      c.(example1_loyalty_Customer_tier) Example1_loyalty_Tier_Silver;
  massert b
.

(** [business_logic::example2_transfer::Account]
    Source: 'src/example2_transfer.rs', lines 1:0-4:1 *)
Record example2_transfer_Account_t :=
mkexample2_transfer_Account_t {
  example2_transfer_Account_id : u32;
  example2_transfer_Account_balance_cents : i64;
}
.

(** [business_logic::example2_transfer::transfer]:
    Source: 'src/example2_transfer.rs', lines 6:0-18:1 *)
Definition example2_transfer_transfer
  (src : example2_transfer_Account_t) (dst : example2_transfer_Account_t)
  (amount_cents : i64) :
  result (bool * example2_transfer_Account_t * example2_transfer_Account_t)
  :=
  if amount_cents s<= 0%i64
  then Ok (false, src, dst)
  else
    if src.(example2_transfer_Account_balance_cents) s< amount_cents
    then Ok (false, src, dst)
    else (
      i <- i64_sub src.(example2_transfer_Account_balance_cents) amount_cents;
      i1 <- i64_add dst.(example2_transfer_Account_balance_cents) amount_cents;
      Ok (true,
        {|
          example2_transfer_Account_id := src.(example2_transfer_Account_id);
          example2_transfer_Account_balance_cents := i
        |},
        {|
          example2_transfer_Account_id := dst.(example2_transfer_Account_id);
          example2_transfer_Account_balance_cents := i1
        |}))
.

(** [business_logic::example2_transfer::run_example]:
    Source: 'src/example2_transfer.rs', lines 20:0-28:1 *)
Definition example2_transfer_run_example : result unit :=
  t <-
    example2_transfer_transfer
      {|
        example2_transfer_Account_id := 1%u32;
        example2_transfer_Account_balance_cents := 10000%i64
      |}
      {|
        example2_transfer_Account_id := 2%u32;
        example2_transfer_Account_balance_cents := 5000%i64
      |} 3000%i64;
  let '(ok, src, dst) := t in
  _ <- massert ok;
  _ <- massert (src.(example2_transfer_Account_balance_cents) s= 7000%i64);
  massert (dst.(example2_transfer_Account_balance_cents) s= 8000%i64)
.

(** [business_logic::example3_inventory::Item]
    Source: 'src/example3_inventory.rs', lines 1:0-5:1 *)
Record example3_inventory_Item_t :=
mkexample3_inventory_Item_t {
  example3_inventory_Item_id : u32;
  example3_inventory_Item_stock : i32;
  example3_inventory_Item_reserved : i32;
}
.

(** [business_logic::example3_inventory::apply_stock_change]:
    Source: 'src/example3_inventory.rs', lines 7:0-25:1 *)
Definition example3_inventory_apply_stock_change
  (item : example3_inventory_Item_t) (delta : i32) :
  result (bool * example3_inventory_Item_t)
  :=
  new_stock <- i32_add item.(example3_inventory_Item_stock) delta;
  if new_stock s< 0%i32
  then
    if item.(example3_inventory_Item_reserved) s> 0%i32
    then
      Ok (false,
        {|
          example3_inventory_Item_id := item.(example3_inventory_Item_id);
          example3_inventory_Item_stock := 0%i32;
          example3_inventory_Item_reserved := 0%i32
        |})
    else
      Ok (false,
        {|
          example3_inventory_Item_id := item.(example3_inventory_Item_id);
          example3_inventory_Item_stock := 0%i32;
          example3_inventory_Item_reserved :=
            item.(example3_inventory_Item_reserved)
        |})
  else
    if item.(example3_inventory_Item_reserved) s> new_stock
    then
      Ok (true,
        {|
          example3_inventory_Item_id := item.(example3_inventory_Item_id);
          example3_inventory_Item_stock := new_stock;
          example3_inventory_Item_reserved := new_stock
        |})
    else
      Ok (true,
        {|
          example3_inventory_Item_id := item.(example3_inventory_Item_id);
          example3_inventory_Item_stock := new_stock;
          example3_inventory_Item_reserved :=
            item.(example3_inventory_Item_reserved)
        |})
.

(** [business_logic::example3_inventory::run_example]:
    Source: 'src/example3_inventory.rs', lines 27:0-43:1 *)
Definition example3_inventory_run_example : result unit :=
  p <-
    example3_inventory_apply_stock_change
      {|
        example3_inventory_Item_id := 10%u32;
        example3_inventory_Item_stock := 5%i32;
        example3_inventory_Item_reserved := 2%i32
      |} (-3)%i32;
  let (ok1, item) := p in
  _ <- massert ok1;
  _ <- massert (item.(example3_inventory_Item_stock) s= 2%i32);
  _ <- massert (item.(example3_inventory_Item_reserved) s= 2%i32);
  p1 <- example3_inventory_apply_stock_change item (-10)%i32;
  let (ok2, item1) := p1 in
  _ <- massert ok2;
  _ <- massert (item1.(example3_inventory_Item_stock) s= 0%i32);
  massert (item1.(example3_inventory_Item_reserved) s= 0%i32)
.

(** [business_logic::example4_order::OrderState]
    Source: 'src/example4_order.rs', lines 2:0-7:1 *)
Inductive example4_order_OrderState_t :=
| Example4_order_OrderState_Created : example4_order_OrderState_t
| Example4_order_OrderState_Paid : example4_order_OrderState_t
| Example4_order_OrderState_Shipped : example4_order_OrderState_t
| Example4_order_OrderState_Cancelled : example4_order_OrderState_t
.

(** [business_logic::example4_order::{core::clone::Clone for business_logic::example4_order::OrderState}::clone]:
    Source: 'src/example4_order.rs', lines 1:9-1:14 *)
Definition example4_order_Clonebusiness_logicexample4_orderOrderState_clone
  (self : example4_order_OrderState_t) : result example4_order_OrderState_t :=
  Ok self
.

(** Trait implementation: [business_logic::example4_order::{core::clone::Clone for business_logic::example4_order::OrderState}]
    Source: 'src/example4_order.rs', lines 1:9-1:14 *)
Definition core_clone_Clonebusiness_logicexample4_orderOrderState :
  core_clone_Clone example4_order_OrderState_t := {|
  core_clone_Clone_clone :=
    example4_order_Clonebusiness_logicexample4_orderOrderState_clone;
|}.

(** Trait implementation: [business_logic::example4_order::{core::marker::Copy for business_logic::example4_order::OrderState}]
    Source: 'src/example4_order.rs', lines 1:16-1:20 *)
Definition core_marker_Copybusiness_logicexample4_orderOrderState :
  core_marker_Copy example4_order_OrderState_t := {|
  cloneInst := core_clone_Clonebusiness_logicexample4_orderOrderState;
|}.

(** [business_logic::example4_order::{core::cmp::PartialEq<business_logic::example4_order::OrderState> for business_logic::example4_order::OrderState}::eq]:
    Source: 'src/example4_order.rs', lines 11:4-19:5 *)
Definition
  example4_order_PartialEqbusiness_logicexample4_orderOrderStatebusiness_logicexample4_orderOrderState_eq
  (self : example4_order_OrderState_t) (other : example4_order_OrderState_t) :
  result bool
  :=
  match self with
  | Example4_order_OrderState_Created =>
    match other with
    | Example4_order_OrderState_Created => Ok true
    | Example4_order_OrderState_Paid => Ok false
    | Example4_order_OrderState_Shipped => Ok false
    | Example4_order_OrderState_Cancelled => Ok false
    end
  | Example4_order_OrderState_Paid =>
    match other with
    | Example4_order_OrderState_Created => Ok false
    | Example4_order_OrderState_Paid => Ok true
    | Example4_order_OrderState_Shipped => Ok false
    | Example4_order_OrderState_Cancelled => Ok false
    end
  | Example4_order_OrderState_Shipped =>
    match other with
    | Example4_order_OrderState_Created => Ok false
    | Example4_order_OrderState_Paid => Ok false
    | Example4_order_OrderState_Shipped => Ok true
    | Example4_order_OrderState_Cancelled => Ok false
    end
  | Example4_order_OrderState_Cancelled =>
    match other with
    | Example4_order_OrderState_Created => Ok false
    | Example4_order_OrderState_Paid => Ok false
    | Example4_order_OrderState_Shipped => Ok false
    | Example4_order_OrderState_Cancelled => Ok true
    end
  end
.

(** Trait implementation: [business_logic::example4_order::{core::cmp::PartialEq<business_logic::example4_order::OrderState> for business_logic::example4_order::OrderState}]
    Source: 'src/example4_order.rs', lines 10:0-20:1 *)
Definition
  core_cmp_PartialEqbusiness_logicexample4_orderOrderStatebusiness_logicexample4_orderOrderState
  : core_cmp_PartialEq_t example4_order_OrderState_t
  example4_order_OrderState_t := {|
  core_cmp_PartialEq_t_eq :=
    example4_order_PartialEqbusiness_logicexample4_orderOrderStatebusiness_logicexample4_orderOrderState_eq;
|}.

(** Trait implementation: [business_logic::example4_order::{core::cmp::Eq for business_logic::example4_order::OrderState}]
    Source: 'src/example4_order.rs', lines 22:0-22:36 *)
Definition core_cmp_Eqbusiness_logicexample4_orderOrderState : core_cmp_Eq_t
  example4_order_OrderState_t := {|
  core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst :=
    core_cmp_PartialEqbusiness_logicexample4_orderOrderStatebusiness_logicexample4_orderOrderState;
|}.

(** [business_logic::example4_order::Event]
    Source: 'src/example4_order.rs', lines 25:0-29:1 *)
Inductive example4_order_Event_t :=
| Example4_order_Event_Pay : example4_order_Event_t
| Example4_order_Event_Ship : example4_order_Event_t
| Example4_order_Event_Cancel : example4_order_Event_t
.

(** [business_logic::example4_order::{core::clone::Clone for business_logic::example4_order::Event}::clone]:
    Source: 'src/example4_order.rs', lines 24:9-24:14 *)
Definition example4_order_Clonebusiness_logicexample4_orderEvent_clone
  (self : example4_order_Event_t) : result example4_order_Event_t :=
  Ok self
.

(** Trait implementation: [business_logic::example4_order::{core::clone::Clone for business_logic::example4_order::Event}]
    Source: 'src/example4_order.rs', lines 24:9-24:14 *)
Definition core_clone_Clonebusiness_logicexample4_orderEvent : core_clone_Clone
  example4_order_Event_t := {|
  core_clone_Clone_clone :=
    example4_order_Clonebusiness_logicexample4_orderEvent_clone;
|}.

(** Trait implementation: [business_logic::example4_order::{core::marker::Copy for business_logic::example4_order::Event}]
    Source: 'src/example4_order.rs', lines 24:16-24:20 *)
Definition core_marker_Copybusiness_logicexample4_orderEvent : core_marker_Copy
  example4_order_Event_t := {|
  cloneInst := core_clone_Clonebusiness_logicexample4_orderEvent;
|}.

(** [business_logic::example4_order::{core::cmp::PartialEq<business_logic::example4_order::Event> for business_logic::example4_order::Event}::eq]:
    Source: 'src/example4_order.rs', lines 32:4-39:5 *)
Definition
  example4_order_PartialEqbusiness_logicexample4_orderEventbusiness_logicexample4_orderEvent_eq
  (self : example4_order_Event_t) (other : example4_order_Event_t) :
  result bool
  :=
  match self with
  | Example4_order_Event_Pay =>
    match other with
    | Example4_order_Event_Pay => Ok true
    | Example4_order_Event_Ship => Ok false
    | Example4_order_Event_Cancel => Ok false
    end
  | Example4_order_Event_Ship =>
    match other with
    | Example4_order_Event_Pay => Ok false
    | Example4_order_Event_Ship => Ok true
    | Example4_order_Event_Cancel => Ok false
    end
  | Example4_order_Event_Cancel =>
    match other with
    | Example4_order_Event_Pay => Ok false
    | Example4_order_Event_Ship => Ok false
    | Example4_order_Event_Cancel => Ok true
    end
  end
.

(** Trait implementation: [business_logic::example4_order::{core::cmp::PartialEq<business_logic::example4_order::Event> for business_logic::example4_order::Event}]
    Source: 'src/example4_order.rs', lines 31:0-40:1 *)
Definition
  core_cmp_PartialEqbusiness_logicexample4_orderEventbusiness_logicexample4_orderEvent
  : core_cmp_PartialEq_t example4_order_Event_t example4_order_Event_t := {|
  core_cmp_PartialEq_t_eq :=
    example4_order_PartialEqbusiness_logicexample4_orderEventbusiness_logicexample4_orderEvent_eq;
|}.

(** Trait implementation: [business_logic::example4_order::{core::cmp::Eq for business_logic::example4_order::Event}]
    Source: 'src/example4_order.rs', lines 42:0-42:31 *)
Definition core_cmp_Eqbusiness_logicexample4_orderEvent : core_cmp_Eq_t
  example4_order_Event_t := {|
  core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst :=
    core_cmp_PartialEqbusiness_logicexample4_orderEventbusiness_logicexample4_orderEvent;
|}.

(** [business_logic::example4_order::apply_event]:
    Source: 'src/example4_order.rs', lines 44:0-89:1 *)
Definition example4_order_apply_event
  (state : example4_order_OrderState_t) (event : example4_order_Event_t) :
  result (bool * example4_order_OrderState_t)
  :=
  match state with
  | Example4_order_OrderState_Created =>
    match event with
    | Example4_order_Event_Pay => Ok (true, Example4_order_OrderState_Paid)
    | Example4_order_Event_Ship =>
      Ok (false, Example4_order_OrderState_Created)
    | Example4_order_Event_Cancel =>
      Ok (true, Example4_order_OrderState_Cancelled)
    end
  | Example4_order_OrderState_Paid =>
    match event with
    | Example4_order_Event_Pay => Ok (false, Example4_order_OrderState_Paid)
    | Example4_order_Event_Ship => Ok (true, Example4_order_OrderState_Shipped)
    | Example4_order_Event_Cancel =>
      Ok (true, Example4_order_OrderState_Cancelled)
    end
  | Example4_order_OrderState_Shipped =>
    Ok (false, Example4_order_OrderState_Shipped)
  | Example4_order_OrderState_Cancelled =>
    Ok (false, Example4_order_OrderState_Cancelled)
  end
.

(** [business_logic::example4_order::run_example]:
    Source: 'src/example4_order.rs', lines 91:0-104:1 *)
Definition example4_order_run_example : result unit :=
  p <-
    example4_order_apply_event Example4_order_OrderState_Created
      Example4_order_Event_Pay;
  let (c1, state) := p in
  _ <- massert c1;
  b <-
    example4_order_PartialEqbusiness_logicexample4_orderOrderStatebusiness_logicexample4_orderOrderState_eq
      state Example4_order_OrderState_Paid;
  _ <- massert b;
  p1 <- example4_order_apply_event state Example4_order_Event_Ship;
  let (c2, state1) := p1 in
  _ <- massert c2;
  b1 <-
    example4_order_PartialEqbusiness_logicexample4_orderOrderStatebusiness_logicexample4_orderOrderState_eq
      state1 Example4_order_OrderState_Shipped;
  _ <- massert b1;
  p2 <- example4_order_apply_event state1 Example4_order_Event_Cancel;
  let (c3, state2) := p2 in
  _ <- massert c3;
  b2 <-
    example4_order_PartialEqbusiness_logicexample4_orderOrderStatebusiness_logicexample4_orderOrderState_eq
      state2 Example4_order_OrderState_Shipped;
  massert b2
.

(** [business_logic::example5_config::LogLevel]
    Source: 'src/example5_config.rs', lines 2:0-7:1 *)
Inductive example5_config_LogLevel_t :=
| Example5_config_LogLevel_Error : example5_config_LogLevel_t
| Example5_config_LogLevel_Warn : example5_config_LogLevel_t
| Example5_config_LogLevel_Info : example5_config_LogLevel_t
| Example5_config_LogLevel_Debug : example5_config_LogLevel_t
.

(** [business_logic::example5_config::{core::clone::Clone for business_logic::example5_config::LogLevel}::clone]:
    Source: 'src/example5_config.rs', lines 1:9-1:14 *)
Definition example5_config_Clonebusiness_logicexample5_configLogLevel_clone
  (self : example5_config_LogLevel_t) : result example5_config_LogLevel_t :=
  Ok self
.

(** Trait implementation: [business_logic::example5_config::{core::clone::Clone for business_logic::example5_config::LogLevel}]
    Source: 'src/example5_config.rs', lines 1:9-1:14 *)
Definition core_clone_Clonebusiness_logicexample5_configLogLevel :
  core_clone_Clone example5_config_LogLevel_t := {|
  core_clone_Clone_clone :=
    example5_config_Clonebusiness_logicexample5_configLogLevel_clone;
|}.

(** Trait implementation: [business_logic::example5_config::{core::marker::Copy for business_logic::example5_config::LogLevel}]
    Source: 'src/example5_config.rs', lines 1:16-1:20 *)
Definition core_marker_Copybusiness_logicexample5_configLogLevel :
  core_marker_Copy example5_config_LogLevel_t := {|
  cloneInst := core_clone_Clonebusiness_logicexample5_configLogLevel;
|}.

(** [business_logic::example5_config::{core::cmp::PartialEq<business_logic::example5_config::LogLevel> for business_logic::example5_config::LogLevel}::eq]:
    Source: 'src/example5_config.rs', lines 11:4-19:5 *)
Definition
  example5_config_PartialEqbusiness_logicexample5_configLogLevelbusiness_logicexample5_configLogLevel_eq
  (self : example5_config_LogLevel_t) (other : example5_config_LogLevel_t) :
  result bool
  :=
  match self with
  | Example5_config_LogLevel_Error =>
    match other with
    | Example5_config_LogLevel_Error => Ok true
    | Example5_config_LogLevel_Warn => Ok false
    | Example5_config_LogLevel_Info => Ok false
    | Example5_config_LogLevel_Debug => Ok false
    end
  | Example5_config_LogLevel_Warn =>
    match other with
    | Example5_config_LogLevel_Error => Ok false
    | Example5_config_LogLevel_Warn => Ok true
    | Example5_config_LogLevel_Info => Ok false
    | Example5_config_LogLevel_Debug => Ok false
    end
  | Example5_config_LogLevel_Info =>
    match other with
    | Example5_config_LogLevel_Error => Ok false
    | Example5_config_LogLevel_Warn => Ok false
    | Example5_config_LogLevel_Info => Ok true
    | Example5_config_LogLevel_Debug => Ok false
    end
  | Example5_config_LogLevel_Debug =>
    match other with
    | Example5_config_LogLevel_Error => Ok false
    | Example5_config_LogLevel_Warn => Ok false
    | Example5_config_LogLevel_Info => Ok false
    | Example5_config_LogLevel_Debug => Ok true
    end
  end
.

(** Trait implementation: [business_logic::example5_config::{core::cmp::PartialEq<business_logic::example5_config::LogLevel> for business_logic::example5_config::LogLevel}]
    Source: 'src/example5_config.rs', lines 10:0-20:1 *)
Definition
  core_cmp_PartialEqbusiness_logicexample5_configLogLevelbusiness_logicexample5_configLogLevel
  : core_cmp_PartialEq_t example5_config_LogLevel_t example5_config_LogLevel_t
  := {|
  core_cmp_PartialEq_t_eq :=
    example5_config_PartialEqbusiness_logicexample5_configLogLevelbusiness_logicexample5_configLogLevel_eq;
|}.

(** Trait implementation: [business_logic::example5_config::{core::cmp::Eq for business_logic::example5_config::LogLevel}]
    Source: 'src/example5_config.rs', lines 22:0-22:34 *)
Definition core_cmp_Eqbusiness_logicexample5_configLogLevel : core_cmp_Eq_t
  example5_config_LogLevel_t := {|
  core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst :=
    core_cmp_PartialEqbusiness_logicexample5_configLogLevelbusiness_logicexample5_configLogLevel;
|}.

(** [business_logic::example5_config::RawConfig]
    Source: 'src/example5_config.rs', lines 25:0-30:1 *)
Record example5_config_RawConfig_t :=
mkexample5_config_RawConfig_t {
  example5_config_RawConfig_max_connections : i32;
  example5_config_RawConfig_timeout_ms : i32;
  example5_config_RawConfig_log_level_code : i32;
}
.

(** [business_logic::example5_config::AppConfig]
    Source: 'src/example5_config.rs', lines 32:0-36:1 *)
Record example5_config_AppConfig_t :=
mkexample5_config_AppConfig_t {
  example5_config_AppConfig_max_connections : u32;
  example5_config_AppConfig_timeout_ms : u32;
  example5_config_AppConfig_log_level : example5_config_LogLevel_t;
}
.

(** [business_logic::example5_config::normalise_config]:
    Source: 'src/example5_config.rs', lines 38:0-75:1 *)
Definition example5_config_normalise_config
  (raw : example5_config_RawConfig_t) : result example5_config_AppConfig_t :=
  if raw.(example5_config_RawConfig_max_connections) s<= 0%i32
  then
    if 100%i32 s< 1%i32
    then
      if 1%i32 s> 10000%i32
      then
        if raw.(example5_config_RawConfig_timeout_ms) s<= 0%i32
        then
          if raw.(example5_config_RawConfig_log_level_code) s= 0%i32
          then (
            i <- scalar_cast I32 U32 10000%i32;
            i1 <- scalar_cast I32 U32 1000%i32;
            Ok
              {|
                example5_config_AppConfig_max_connections := i;
                example5_config_AppConfig_timeout_ms := i1;
                example5_config_AppConfig_log_level :=
                  Example5_config_LogLevel_Error
              |})
          else
            if raw.(example5_config_RawConfig_log_level_code) s= 1%i32
            then (
              i <- scalar_cast I32 U32 10000%i32;
              i1 <- scalar_cast I32 U32 1000%i32;
              Ok
                {|
                  example5_config_AppConfig_max_connections := i;
                  example5_config_AppConfig_timeout_ms := i1;
                  example5_config_AppConfig_log_level :=
                    Example5_config_LogLevel_Warn
                |})
            else
              if raw.(example5_config_RawConfig_log_level_code) s= 2%i32
              then (
                i <- scalar_cast I32 U32 10000%i32;
                i1 <- scalar_cast I32 U32 1000%i32;
                Ok
                  {|
                    example5_config_AppConfig_max_connections := i;
                    example5_config_AppConfig_timeout_ms := i1;
                    example5_config_AppConfig_log_level :=
                      Example5_config_LogLevel_Info
                  |})
              else
                if raw.(example5_config_RawConfig_log_level_code) s= 3%i32
                then (
                  i <- scalar_cast I32 U32 10000%i32;
                  i1 <- scalar_cast I32 U32 1000%i32;
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Debug
                    |})
                else (
                  i <- scalar_cast I32 U32 10000%i32;
                  i1 <- scalar_cast I32 U32 1000%i32;
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Info
                    |})
        else
          if raw.(example5_config_RawConfig_log_level_code) s= 0%i32
          then (
            i <- scalar_cast I32 U32 10000%i32;
            i1 <-
              scalar_cast I32 U32 raw.(example5_config_RawConfig_timeout_ms);
            Ok
              {|
                example5_config_AppConfig_max_connections := i;
                example5_config_AppConfig_timeout_ms := i1;
                example5_config_AppConfig_log_level :=
                  Example5_config_LogLevel_Error
              |})
          else
            if raw.(example5_config_RawConfig_log_level_code) s= 1%i32
            then (
              i <- scalar_cast I32 U32 10000%i32;
              i1 <-
                scalar_cast I32 U32 raw.(example5_config_RawConfig_timeout_ms);
              Ok
                {|
                  example5_config_AppConfig_max_connections := i;
                  example5_config_AppConfig_timeout_ms := i1;
                  example5_config_AppConfig_log_level :=
                    Example5_config_LogLevel_Warn
                |})
            else
              if raw.(example5_config_RawConfig_log_level_code) s= 2%i32
              then (
                i <- scalar_cast I32 U32 10000%i32;
                i1 <-
                  scalar_cast I32 U32
                    raw.(example5_config_RawConfig_timeout_ms);
                Ok
                  {|
                    example5_config_AppConfig_max_connections := i;
                    example5_config_AppConfig_timeout_ms := i1;
                    example5_config_AppConfig_log_level :=
                      Example5_config_LogLevel_Info
                  |})
              else
                if raw.(example5_config_RawConfig_log_level_code) s= 3%i32
                then (
                  i <- scalar_cast I32 U32 10000%i32;
                  i1 <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_timeout_ms);
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Debug
                    |})
                else (
                  i <- scalar_cast I32 U32 10000%i32;
                  i1 <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_timeout_ms);
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Info
                    |})
      else
        if raw.(example5_config_RawConfig_timeout_ms) s<= 0%i32
        then
          if raw.(example5_config_RawConfig_log_level_code) s= 0%i32
          then (
            i <- scalar_cast I32 U32 1%i32;
            i1 <- scalar_cast I32 U32 1000%i32;
            Ok
              {|
                example5_config_AppConfig_max_connections := i;
                example5_config_AppConfig_timeout_ms := i1;
                example5_config_AppConfig_log_level :=
                  Example5_config_LogLevel_Error
              |})
          else
            if raw.(example5_config_RawConfig_log_level_code) s= 1%i32
            then (
              i <- scalar_cast I32 U32 1%i32;
              i1 <- scalar_cast I32 U32 1000%i32;
              Ok
                {|
                  example5_config_AppConfig_max_connections := i;
                  example5_config_AppConfig_timeout_ms := i1;
                  example5_config_AppConfig_log_level :=
                    Example5_config_LogLevel_Warn
                |})
            else
              if raw.(example5_config_RawConfig_log_level_code) s= 2%i32
              then (
                i <- scalar_cast I32 U32 1%i32;
                i1 <- scalar_cast I32 U32 1000%i32;
                Ok
                  {|
                    example5_config_AppConfig_max_connections := i;
                    example5_config_AppConfig_timeout_ms := i1;
                    example5_config_AppConfig_log_level :=
                      Example5_config_LogLevel_Info
                  |})
              else
                if raw.(example5_config_RawConfig_log_level_code) s= 3%i32
                then (
                  i <- scalar_cast I32 U32 1%i32;
                  i1 <- scalar_cast I32 U32 1000%i32;
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Debug
                    |})
                else (
                  i <- scalar_cast I32 U32 1%i32;
                  i1 <- scalar_cast I32 U32 1000%i32;
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Info
                    |})
        else
          if raw.(example5_config_RawConfig_log_level_code) s= 0%i32
          then (
            i <- scalar_cast I32 U32 1%i32;
            i1 <-
              scalar_cast I32 U32 raw.(example5_config_RawConfig_timeout_ms);
            Ok
              {|
                example5_config_AppConfig_max_connections := i;
                example5_config_AppConfig_timeout_ms := i1;
                example5_config_AppConfig_log_level :=
                  Example5_config_LogLevel_Error
              |})
          else
            if raw.(example5_config_RawConfig_log_level_code) s= 1%i32
            then (
              i <- scalar_cast I32 U32 1%i32;
              i1 <-
                scalar_cast I32 U32 raw.(example5_config_RawConfig_timeout_ms);
              Ok
                {|
                  example5_config_AppConfig_max_connections := i;
                  example5_config_AppConfig_timeout_ms := i1;
                  example5_config_AppConfig_log_level :=
                    Example5_config_LogLevel_Warn
                |})
            else
              if raw.(example5_config_RawConfig_log_level_code) s= 2%i32
              then (
                i <- scalar_cast I32 U32 1%i32;
                i1 <-
                  scalar_cast I32 U32
                    raw.(example5_config_RawConfig_timeout_ms);
                Ok
                  {|
                    example5_config_AppConfig_max_connections := i;
                    example5_config_AppConfig_timeout_ms := i1;
                    example5_config_AppConfig_log_level :=
                      Example5_config_LogLevel_Info
                  |})
              else
                if raw.(example5_config_RawConfig_log_level_code) s= 3%i32
                then (
                  i <- scalar_cast I32 U32 1%i32;
                  i1 <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_timeout_ms);
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Debug
                    |})
                else (
                  i <- scalar_cast I32 U32 1%i32;
                  i1 <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_timeout_ms);
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Info
                    |})
    else
      if 100%i32 s> 10000%i32
      then
        if raw.(example5_config_RawConfig_timeout_ms) s<= 0%i32
        then
          if raw.(example5_config_RawConfig_log_level_code) s= 0%i32
          then (
            i <- scalar_cast I32 U32 10000%i32;
            i1 <- scalar_cast I32 U32 1000%i32;
            Ok
              {|
                example5_config_AppConfig_max_connections := i;
                example5_config_AppConfig_timeout_ms := i1;
                example5_config_AppConfig_log_level :=
                  Example5_config_LogLevel_Error
              |})
          else
            if raw.(example5_config_RawConfig_log_level_code) s= 1%i32
            then (
              i <- scalar_cast I32 U32 10000%i32;
              i1 <- scalar_cast I32 U32 1000%i32;
              Ok
                {|
                  example5_config_AppConfig_max_connections := i;
                  example5_config_AppConfig_timeout_ms := i1;
                  example5_config_AppConfig_log_level :=
                    Example5_config_LogLevel_Warn
                |})
            else
              if raw.(example5_config_RawConfig_log_level_code) s= 2%i32
              then (
                i <- scalar_cast I32 U32 10000%i32;
                i1 <- scalar_cast I32 U32 1000%i32;
                Ok
                  {|
                    example5_config_AppConfig_max_connections := i;
                    example5_config_AppConfig_timeout_ms := i1;
                    example5_config_AppConfig_log_level :=
                      Example5_config_LogLevel_Info
                  |})
              else
                if raw.(example5_config_RawConfig_log_level_code) s= 3%i32
                then (
                  i <- scalar_cast I32 U32 10000%i32;
                  i1 <- scalar_cast I32 U32 1000%i32;
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Debug
                    |})
                else (
                  i <- scalar_cast I32 U32 10000%i32;
                  i1 <- scalar_cast I32 U32 1000%i32;
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Info
                    |})
        else
          if raw.(example5_config_RawConfig_log_level_code) s= 0%i32
          then (
            i <- scalar_cast I32 U32 10000%i32;
            i1 <-
              scalar_cast I32 U32 raw.(example5_config_RawConfig_timeout_ms);
            Ok
              {|
                example5_config_AppConfig_max_connections := i;
                example5_config_AppConfig_timeout_ms := i1;
                example5_config_AppConfig_log_level :=
                  Example5_config_LogLevel_Error
              |})
          else
            if raw.(example5_config_RawConfig_log_level_code) s= 1%i32
            then (
              i <- scalar_cast I32 U32 10000%i32;
              i1 <-
                scalar_cast I32 U32 raw.(example5_config_RawConfig_timeout_ms);
              Ok
                {|
                  example5_config_AppConfig_max_connections := i;
                  example5_config_AppConfig_timeout_ms := i1;
                  example5_config_AppConfig_log_level :=
                    Example5_config_LogLevel_Warn
                |})
            else
              if raw.(example5_config_RawConfig_log_level_code) s= 2%i32
              then (
                i <- scalar_cast I32 U32 10000%i32;
                i1 <-
                  scalar_cast I32 U32
                    raw.(example5_config_RawConfig_timeout_ms);
                Ok
                  {|
                    example5_config_AppConfig_max_connections := i;
                    example5_config_AppConfig_timeout_ms := i1;
                    example5_config_AppConfig_log_level :=
                      Example5_config_LogLevel_Info
                  |})
              else
                if raw.(example5_config_RawConfig_log_level_code) s= 3%i32
                then (
                  i <- scalar_cast I32 U32 10000%i32;
                  i1 <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_timeout_ms);
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Debug
                    |})
                else (
                  i <- scalar_cast I32 U32 10000%i32;
                  i1 <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_timeout_ms);
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Info
                    |})
      else
        if raw.(example5_config_RawConfig_timeout_ms) s<= 0%i32
        then
          if raw.(example5_config_RawConfig_log_level_code) s= 0%i32
          then (
            i <- scalar_cast I32 U32 100%i32;
            i1 <- scalar_cast I32 U32 1000%i32;
            Ok
              {|
                example5_config_AppConfig_max_connections := i;
                example5_config_AppConfig_timeout_ms := i1;
                example5_config_AppConfig_log_level :=
                  Example5_config_LogLevel_Error
              |})
          else
            if raw.(example5_config_RawConfig_log_level_code) s= 1%i32
            then (
              i <- scalar_cast I32 U32 100%i32;
              i1 <- scalar_cast I32 U32 1000%i32;
              Ok
                {|
                  example5_config_AppConfig_max_connections := i;
                  example5_config_AppConfig_timeout_ms := i1;
                  example5_config_AppConfig_log_level :=
                    Example5_config_LogLevel_Warn
                |})
            else
              if raw.(example5_config_RawConfig_log_level_code) s= 2%i32
              then (
                i <- scalar_cast I32 U32 100%i32;
                i1 <- scalar_cast I32 U32 1000%i32;
                Ok
                  {|
                    example5_config_AppConfig_max_connections := i;
                    example5_config_AppConfig_timeout_ms := i1;
                    example5_config_AppConfig_log_level :=
                      Example5_config_LogLevel_Info
                  |})
              else
                if raw.(example5_config_RawConfig_log_level_code) s= 3%i32
                then (
                  i <- scalar_cast I32 U32 100%i32;
                  i1 <- scalar_cast I32 U32 1000%i32;
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Debug
                    |})
                else (
                  i <- scalar_cast I32 U32 100%i32;
                  i1 <- scalar_cast I32 U32 1000%i32;
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Info
                    |})
        else
          if raw.(example5_config_RawConfig_log_level_code) s= 0%i32
          then (
            i <- scalar_cast I32 U32 100%i32;
            i1 <-
              scalar_cast I32 U32 raw.(example5_config_RawConfig_timeout_ms);
            Ok
              {|
                example5_config_AppConfig_max_connections := i;
                example5_config_AppConfig_timeout_ms := i1;
                example5_config_AppConfig_log_level :=
                  Example5_config_LogLevel_Error
              |})
          else
            if raw.(example5_config_RawConfig_log_level_code) s= 1%i32
            then (
              i <- scalar_cast I32 U32 100%i32;
              i1 <-
                scalar_cast I32 U32 raw.(example5_config_RawConfig_timeout_ms);
              Ok
                {|
                  example5_config_AppConfig_max_connections := i;
                  example5_config_AppConfig_timeout_ms := i1;
                  example5_config_AppConfig_log_level :=
                    Example5_config_LogLevel_Warn
                |})
            else
              if raw.(example5_config_RawConfig_log_level_code) s= 2%i32
              then (
                i <- scalar_cast I32 U32 100%i32;
                i1 <-
                  scalar_cast I32 U32
                    raw.(example5_config_RawConfig_timeout_ms);
                Ok
                  {|
                    example5_config_AppConfig_max_connections := i;
                    example5_config_AppConfig_timeout_ms := i1;
                    example5_config_AppConfig_log_level :=
                      Example5_config_LogLevel_Info
                  |})
              else
                if raw.(example5_config_RawConfig_log_level_code) s= 3%i32
                then (
                  i <- scalar_cast I32 U32 100%i32;
                  i1 <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_timeout_ms);
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Debug
                    |})
                else (
                  i <- scalar_cast I32 U32 100%i32;
                  i1 <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_timeout_ms);
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Info
                    |})
  else
    if raw.(example5_config_RawConfig_max_connections) s< 1%i32
    then
      if 1%i32 s> 10000%i32
      then
        if raw.(example5_config_RawConfig_timeout_ms) s<= 0%i32
        then
          if raw.(example5_config_RawConfig_log_level_code) s= 0%i32
          then (
            i <- scalar_cast I32 U32 10000%i32;
            i1 <- scalar_cast I32 U32 1000%i32;
            Ok
              {|
                example5_config_AppConfig_max_connections := i;
                example5_config_AppConfig_timeout_ms := i1;
                example5_config_AppConfig_log_level :=
                  Example5_config_LogLevel_Error
              |})
          else
            if raw.(example5_config_RawConfig_log_level_code) s= 1%i32
            then (
              i <- scalar_cast I32 U32 10000%i32;
              i1 <- scalar_cast I32 U32 1000%i32;
              Ok
                {|
                  example5_config_AppConfig_max_connections := i;
                  example5_config_AppConfig_timeout_ms := i1;
                  example5_config_AppConfig_log_level :=
                    Example5_config_LogLevel_Warn
                |})
            else
              if raw.(example5_config_RawConfig_log_level_code) s= 2%i32
              then (
                i <- scalar_cast I32 U32 10000%i32;
                i1 <- scalar_cast I32 U32 1000%i32;
                Ok
                  {|
                    example5_config_AppConfig_max_connections := i;
                    example5_config_AppConfig_timeout_ms := i1;
                    example5_config_AppConfig_log_level :=
                      Example5_config_LogLevel_Info
                  |})
              else
                if raw.(example5_config_RawConfig_log_level_code) s= 3%i32
                then (
                  i <- scalar_cast I32 U32 10000%i32;
                  i1 <- scalar_cast I32 U32 1000%i32;
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Debug
                    |})
                else (
                  i <- scalar_cast I32 U32 10000%i32;
                  i1 <- scalar_cast I32 U32 1000%i32;
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Info
                    |})
        else
          if raw.(example5_config_RawConfig_log_level_code) s= 0%i32
          then (
            i <- scalar_cast I32 U32 10000%i32;
            i1 <-
              scalar_cast I32 U32 raw.(example5_config_RawConfig_timeout_ms);
            Ok
              {|
                example5_config_AppConfig_max_connections := i;
                example5_config_AppConfig_timeout_ms := i1;
                example5_config_AppConfig_log_level :=
                  Example5_config_LogLevel_Error
              |})
          else
            if raw.(example5_config_RawConfig_log_level_code) s= 1%i32
            then (
              i <- scalar_cast I32 U32 10000%i32;
              i1 <-
                scalar_cast I32 U32 raw.(example5_config_RawConfig_timeout_ms);
              Ok
                {|
                  example5_config_AppConfig_max_connections := i;
                  example5_config_AppConfig_timeout_ms := i1;
                  example5_config_AppConfig_log_level :=
                    Example5_config_LogLevel_Warn
                |})
            else
              if raw.(example5_config_RawConfig_log_level_code) s= 2%i32
              then (
                i <- scalar_cast I32 U32 10000%i32;
                i1 <-
                  scalar_cast I32 U32
                    raw.(example5_config_RawConfig_timeout_ms);
                Ok
                  {|
                    example5_config_AppConfig_max_connections := i;
                    example5_config_AppConfig_timeout_ms := i1;
                    example5_config_AppConfig_log_level :=
                      Example5_config_LogLevel_Info
                  |})
              else
                if raw.(example5_config_RawConfig_log_level_code) s= 3%i32
                then (
                  i <- scalar_cast I32 U32 10000%i32;
                  i1 <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_timeout_ms);
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Debug
                    |})
                else (
                  i <- scalar_cast I32 U32 10000%i32;
                  i1 <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_timeout_ms);
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Info
                    |})
      else
        if raw.(example5_config_RawConfig_timeout_ms) s<= 0%i32
        then
          if raw.(example5_config_RawConfig_log_level_code) s= 0%i32
          then (
            i <- scalar_cast I32 U32 1%i32;
            i1 <- scalar_cast I32 U32 1000%i32;
            Ok
              {|
                example5_config_AppConfig_max_connections := i;
                example5_config_AppConfig_timeout_ms := i1;
                example5_config_AppConfig_log_level :=
                  Example5_config_LogLevel_Error
              |})
          else
            if raw.(example5_config_RawConfig_log_level_code) s= 1%i32
            then (
              i <- scalar_cast I32 U32 1%i32;
              i1 <- scalar_cast I32 U32 1000%i32;
              Ok
                {|
                  example5_config_AppConfig_max_connections := i;
                  example5_config_AppConfig_timeout_ms := i1;
                  example5_config_AppConfig_log_level :=
                    Example5_config_LogLevel_Warn
                |})
            else
              if raw.(example5_config_RawConfig_log_level_code) s= 2%i32
              then (
                i <- scalar_cast I32 U32 1%i32;
                i1 <- scalar_cast I32 U32 1000%i32;
                Ok
                  {|
                    example5_config_AppConfig_max_connections := i;
                    example5_config_AppConfig_timeout_ms := i1;
                    example5_config_AppConfig_log_level :=
                      Example5_config_LogLevel_Info
                  |})
              else
                if raw.(example5_config_RawConfig_log_level_code) s= 3%i32
                then (
                  i <- scalar_cast I32 U32 1%i32;
                  i1 <- scalar_cast I32 U32 1000%i32;
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Debug
                    |})
                else (
                  i <- scalar_cast I32 U32 1%i32;
                  i1 <- scalar_cast I32 U32 1000%i32;
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Info
                    |})
        else
          if raw.(example5_config_RawConfig_log_level_code) s= 0%i32
          then (
            i <- scalar_cast I32 U32 1%i32;
            i1 <-
              scalar_cast I32 U32 raw.(example5_config_RawConfig_timeout_ms);
            Ok
              {|
                example5_config_AppConfig_max_connections := i;
                example5_config_AppConfig_timeout_ms := i1;
                example5_config_AppConfig_log_level :=
                  Example5_config_LogLevel_Error
              |})
          else
            if raw.(example5_config_RawConfig_log_level_code) s= 1%i32
            then (
              i <- scalar_cast I32 U32 1%i32;
              i1 <-
                scalar_cast I32 U32 raw.(example5_config_RawConfig_timeout_ms);
              Ok
                {|
                  example5_config_AppConfig_max_connections := i;
                  example5_config_AppConfig_timeout_ms := i1;
                  example5_config_AppConfig_log_level :=
                    Example5_config_LogLevel_Warn
                |})
            else
              if raw.(example5_config_RawConfig_log_level_code) s= 2%i32
              then (
                i <- scalar_cast I32 U32 1%i32;
                i1 <-
                  scalar_cast I32 U32
                    raw.(example5_config_RawConfig_timeout_ms);
                Ok
                  {|
                    example5_config_AppConfig_max_connections := i;
                    example5_config_AppConfig_timeout_ms := i1;
                    example5_config_AppConfig_log_level :=
                      Example5_config_LogLevel_Info
                  |})
              else
                if raw.(example5_config_RawConfig_log_level_code) s= 3%i32
                then (
                  i <- scalar_cast I32 U32 1%i32;
                  i1 <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_timeout_ms);
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Debug
                    |})
                else (
                  i <- scalar_cast I32 U32 1%i32;
                  i1 <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_timeout_ms);
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Info
                    |})
    else
      if raw.(example5_config_RawConfig_max_connections) s> 10000%i32
      then
        if raw.(example5_config_RawConfig_timeout_ms) s<= 0%i32
        then
          if raw.(example5_config_RawConfig_log_level_code) s= 0%i32
          then (
            i <- scalar_cast I32 U32 10000%i32;
            i1 <- scalar_cast I32 U32 1000%i32;
            Ok
              {|
                example5_config_AppConfig_max_connections := i;
                example5_config_AppConfig_timeout_ms := i1;
                example5_config_AppConfig_log_level :=
                  Example5_config_LogLevel_Error
              |})
          else
            if raw.(example5_config_RawConfig_log_level_code) s= 1%i32
            then (
              i <- scalar_cast I32 U32 10000%i32;
              i1 <- scalar_cast I32 U32 1000%i32;
              Ok
                {|
                  example5_config_AppConfig_max_connections := i;
                  example5_config_AppConfig_timeout_ms := i1;
                  example5_config_AppConfig_log_level :=
                    Example5_config_LogLevel_Warn
                |})
            else
              if raw.(example5_config_RawConfig_log_level_code) s= 2%i32
              then (
                i <- scalar_cast I32 U32 10000%i32;
                i1 <- scalar_cast I32 U32 1000%i32;
                Ok
                  {|
                    example5_config_AppConfig_max_connections := i;
                    example5_config_AppConfig_timeout_ms := i1;
                    example5_config_AppConfig_log_level :=
                      Example5_config_LogLevel_Info
                  |})
              else
                if raw.(example5_config_RawConfig_log_level_code) s= 3%i32
                then (
                  i <- scalar_cast I32 U32 10000%i32;
                  i1 <- scalar_cast I32 U32 1000%i32;
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Debug
                    |})
                else (
                  i <- scalar_cast I32 U32 10000%i32;
                  i1 <- scalar_cast I32 U32 1000%i32;
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Info
                    |})
        else
          if raw.(example5_config_RawConfig_log_level_code) s= 0%i32
          then (
            i <- scalar_cast I32 U32 10000%i32;
            i1 <-
              scalar_cast I32 U32 raw.(example5_config_RawConfig_timeout_ms);
            Ok
              {|
                example5_config_AppConfig_max_connections := i;
                example5_config_AppConfig_timeout_ms := i1;
                example5_config_AppConfig_log_level :=
                  Example5_config_LogLevel_Error
              |})
          else
            if raw.(example5_config_RawConfig_log_level_code) s= 1%i32
            then (
              i <- scalar_cast I32 U32 10000%i32;
              i1 <-
                scalar_cast I32 U32 raw.(example5_config_RawConfig_timeout_ms);
              Ok
                {|
                  example5_config_AppConfig_max_connections := i;
                  example5_config_AppConfig_timeout_ms := i1;
                  example5_config_AppConfig_log_level :=
                    Example5_config_LogLevel_Warn
                |})
            else
              if raw.(example5_config_RawConfig_log_level_code) s= 2%i32
              then (
                i <- scalar_cast I32 U32 10000%i32;
                i1 <-
                  scalar_cast I32 U32
                    raw.(example5_config_RawConfig_timeout_ms);
                Ok
                  {|
                    example5_config_AppConfig_max_connections := i;
                    example5_config_AppConfig_timeout_ms := i1;
                    example5_config_AppConfig_log_level :=
                      Example5_config_LogLevel_Info
                  |})
              else
                if raw.(example5_config_RawConfig_log_level_code) s= 3%i32
                then (
                  i <- scalar_cast I32 U32 10000%i32;
                  i1 <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_timeout_ms);
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Debug
                    |})
                else (
                  i <- scalar_cast I32 U32 10000%i32;
                  i1 <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_timeout_ms);
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Info
                    |})
      else
        if raw.(example5_config_RawConfig_timeout_ms) s<= 0%i32
        then
          if raw.(example5_config_RawConfig_log_level_code) s= 0%i32
          then (
            i <-
              scalar_cast I32 U32
                raw.(example5_config_RawConfig_max_connections);
            i1 <- scalar_cast I32 U32 1000%i32;
            Ok
              {|
                example5_config_AppConfig_max_connections := i;
                example5_config_AppConfig_timeout_ms := i1;
                example5_config_AppConfig_log_level :=
                  Example5_config_LogLevel_Error
              |})
          else
            if raw.(example5_config_RawConfig_log_level_code) s= 1%i32
            then (
              i <-
                scalar_cast I32 U32
                  raw.(example5_config_RawConfig_max_connections);
              i1 <- scalar_cast I32 U32 1000%i32;
              Ok
                {|
                  example5_config_AppConfig_max_connections := i;
                  example5_config_AppConfig_timeout_ms := i1;
                  example5_config_AppConfig_log_level :=
                    Example5_config_LogLevel_Warn
                |})
            else
              if raw.(example5_config_RawConfig_log_level_code) s= 2%i32
              then (
                i <-
                  scalar_cast I32 U32
                    raw.(example5_config_RawConfig_max_connections);
                i1 <- scalar_cast I32 U32 1000%i32;
                Ok
                  {|
                    example5_config_AppConfig_max_connections := i;
                    example5_config_AppConfig_timeout_ms := i1;
                    example5_config_AppConfig_log_level :=
                      Example5_config_LogLevel_Info
                  |})
              else
                if raw.(example5_config_RawConfig_log_level_code) s= 3%i32
                then (
                  i <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_max_connections);
                  i1 <- scalar_cast I32 U32 1000%i32;
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Debug
                    |})
                else (
                  i <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_max_connections);
                  i1 <- scalar_cast I32 U32 1000%i32;
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Info
                    |})
        else
          if raw.(example5_config_RawConfig_log_level_code) s= 0%i32
          then (
            i <-
              scalar_cast I32 U32
                raw.(example5_config_RawConfig_max_connections);
            i1 <-
              scalar_cast I32 U32 raw.(example5_config_RawConfig_timeout_ms);
            Ok
              {|
                example5_config_AppConfig_max_connections := i;
                example5_config_AppConfig_timeout_ms := i1;
                example5_config_AppConfig_log_level :=
                  Example5_config_LogLevel_Error
              |})
          else
            if raw.(example5_config_RawConfig_log_level_code) s= 1%i32
            then (
              i <-
                scalar_cast I32 U32
                  raw.(example5_config_RawConfig_max_connections);
              i1 <-
                scalar_cast I32 U32 raw.(example5_config_RawConfig_timeout_ms);
              Ok
                {|
                  example5_config_AppConfig_max_connections := i;
                  example5_config_AppConfig_timeout_ms := i1;
                  example5_config_AppConfig_log_level :=
                    Example5_config_LogLevel_Warn
                |})
            else
              if raw.(example5_config_RawConfig_log_level_code) s= 2%i32
              then (
                i <-
                  scalar_cast I32 U32
                    raw.(example5_config_RawConfig_max_connections);
                i1 <-
                  scalar_cast I32 U32
                    raw.(example5_config_RawConfig_timeout_ms);
                Ok
                  {|
                    example5_config_AppConfig_max_connections := i;
                    example5_config_AppConfig_timeout_ms := i1;
                    example5_config_AppConfig_log_level :=
                      Example5_config_LogLevel_Info
                  |})
              else
                if raw.(example5_config_RawConfig_log_level_code) s= 3%i32
                then (
                  i <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_max_connections);
                  i1 <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_timeout_ms);
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Debug
                    |})
                else (
                  i <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_max_connections);
                  i1 <-
                    scalar_cast I32 U32
                      raw.(example5_config_RawConfig_timeout_ms);
                  Ok
                    {|
                      example5_config_AppConfig_max_connections := i;
                      example5_config_AppConfig_timeout_ms := i1;
                      example5_config_AppConfig_log_level :=
                        Example5_config_LogLevel_Info
                    |})
.

(** [business_logic::example5_config::run_example]:
    Source: 'src/example5_config.rs', lines 77:0-88:1 *)
Definition example5_config_run_example : result unit :=
  cfg <-
    example5_config_normalise_config
      {|
        example5_config_RawConfig_max_connections := (-5)%i32;
        example5_config_RawConfig_timeout_ms := 0%i32;
        example5_config_RawConfig_log_level_code := 7%i32
      |};
  _ <- massert (cfg.(example5_config_AppConfig_max_connections) s= 100%u32);
  _ <- massert (cfg.(example5_config_AppConfig_timeout_ms) s= 1000%u32);
  b <-
    example5_config_PartialEqbusiness_logicexample5_configLogLevelbusiness_logicexample5_configLogLevel_eq
      cfg.(example5_config_AppConfig_log_level) Example5_config_LogLevel_Info;
  massert b
.

(** [business_logic::example6_grading::Components]
    Source: 'src/example6_grading.rs', lines 1:0-5:1 *)
Record example6_grading_Components_t :=
mkexample6_grading_Components_t {
  example6_grading_Components_exam : u32;
  example6_grading_Components_assignments : u32;
  example6_grading_Components_participation : u32;
}
.

(** [business_logic::example6_grading::compute_final_mark]:
    Source: 'src/example6_grading.rs', lines 7:0-22:1 *)
Definition example6_grading_compute_final_mark
  (c : example6_grading_Components_t) : result u32 :=
  if c.(example6_grading_Components_exam) s< 40%u32
  then Ok 49%u32
  else (
    exam_part <- u32_mul 4%u32 c.(example6_grading_Components_exam);
    assign_part <- u32_mul 4%u32 c.(example6_grading_Components_assignments);
    part_part <- u32_mul 2%u32 c.(example6_grading_Components_participation);
    i <- u32_add exam_part assign_part;
    sum <- u32_add i part_part;
    u32_div sum 10%u32)
.

(** [business_logic::example6_grading::run_example]:
    Source: 'src/example6_grading.rs', lines 24:0-33:1 *)
Definition example6_grading_run_example : result unit :=
  g1 <-
    example6_grading_compute_final_mark
      {|
        example6_grading_Components_exam := 35%u32;
        example6_grading_Components_assignments := 90%u32;
        example6_grading_Components_participation := 100%u32
      |};
  _ <- massert (g1 s= 49%u32);
  g2 <-
    example6_grading_compute_final_mark
      {|
        example6_grading_Components_exam := 80%u32;
        example6_grading_Components_assignments := 70%u32;
        example6_grading_Components_participation := 50%u32
      |};
  massert (g2 s= 70%u32)
.

(** [business_logic::example7_moving_average::moving_average_3]: loop 0:
    Source: 'src/example7_moving_average.rs', lines 13:4-34:5 *)
Fixpoint example7_moving_average_moving_average_3_loop
  (n : usize) (m : usize) (data : slice i32) (out : slice i32) (i : usize) :
  result (slice i32)
  :=
  if i s< n
  then
    if i s< m
    then
      if i s> 0%usize
      then (
        i1 <- usize_sub i 1%usize;
        i2 <- slice_index_usize data i1;
        sum <- i32_add 0%i32 i2;
        count <- i32_add 0%i32 1%i32;
        i3 <- slice_index_usize data i;
        sum1 <- i32_add sum i3;
        count1 <- i32_add count 1%i32;
        ip1 <- usize_add i 1%usize;
        if ip1 s< n
        then (
          i4 <- slice_index_usize data ip1;
          sum2 <- i32_add sum1 i4;
          count2 <- i32_add count1 1%i32;
          i5 <- i32_div sum2 count2;
          out1 <- slice_update_usize out i i5;
          example7_moving_average_moving_average_3_loop n m data out1 ip1)
        else (
          i4 <- i32_div sum1 count1;
          out1 <- slice_update_usize out i i4;
          example7_moving_average_moving_average_3_loop n m data out1 ip1))
      else (
        i1 <- slice_index_usize data i;
        sum <- i32_add 0%i32 i1;
        count <- i32_add 0%i32 1%i32;
        ip1 <- usize_add i 1%usize;
        if ip1 s< n
        then (
          i2 <- slice_index_usize data ip1;
          sum1 <- i32_add sum i2;
          count1 <- i32_add count 1%i32;
          i3 <- i32_div sum1 count1;
          out1 <- slice_update_usize out i i3;
          example7_moving_average_moving_average_3_loop n m data out1 ip1)
        else (
          i2 <- i32_div sum count;
          out1 <- slice_update_usize out i i2;
          example7_moving_average_moving_average_3_loop n m data out1 ip1))
    else Ok out
  else Ok out
.

(** [business_logic::example7_moving_average::moving_average_3]:
    Source: 'src/example7_moving_average.rs', lines 4:0-35:1 *)
Definition example7_moving_average_moving_average_3
  (data : slice i32) (out : slice i32) : result (slice i32) :=
  let n := slice_len data in
  let m := slice_len out in
  if n s= 0%usize
  then Ok out
  else
    if m s= 0%usize
    then Ok out
    else example7_moving_average_moving_average_3_loop n m data out 0%usize
.

(** [business_logic::example7_moving_average::run_example]:
    Source: 'src/example7_moving_average.rs', lines 38:0-53:1 *)
Definition example7_moving_average_run_example : result unit :=
  let out := array_repeat 4%usize 0%i32 in
  let s := array_to_slice (mk_array 4%usize [ 1%i32; 3%i32; 5%i32; 7%i32 ]) in
  let (s1, to_slice_mut_back) := array_to_slice_mut out in
  s2 <- example7_moving_average_moving_average_3 s s1;
  let out1 := to_slice_mut_back s2 in
  i <- array_index_usize out1 0%usize;
  _ <- massert (i s= 2%i32);
  i1 <- array_index_usize out1 1%usize;
  _ <- massert (i1 s= 3%i32);
  i2 <- array_index_usize out1 2%usize;
  _ <- massert (i2 s= 5%i32);
  i3 <- array_index_usize out1 3%usize;
  massert (i3 s= 6%i32)
.

(** [business_logic::example8_intervals::Interval]
    Source: 'src/example8_intervals.rs', lines 2:0-5:1 *)
Record example8_intervals_Interval_t :=
mkexample8_intervals_Interval_t {
  example8_intervals_Interval_start : i32;
  example8_intervals_Interval_end : i32;
}
.

(** [business_logic::example8_intervals::{core::clone::Clone for business_logic::example8_intervals::Interval}::clone]:
    Source: 'src/example8_intervals.rs', lines 1:9-1:14 *)
Definition
  example8_intervals_Clonebusiness_logicexample8_intervalsInterval_clone
  (self : example8_intervals_Interval_t) :
  result example8_intervals_Interval_t
  :=
  Ok self
.

(** Trait implementation: [business_logic::example8_intervals::{core::clone::Clone for business_logic::example8_intervals::Interval}]
    Source: 'src/example8_intervals.rs', lines 1:9-1:14 *)
Definition core_clone_Clonebusiness_logicexample8_intervalsInterval :
  core_clone_Clone example8_intervals_Interval_t := {|
  core_clone_Clone_clone :=
    example8_intervals_Clonebusiness_logicexample8_intervalsInterval_clone;
|}.

(** Trait implementation: [business_logic::example8_intervals::{core::marker::Copy for business_logic::example8_intervals::Interval}]
    Source: 'src/example8_intervals.rs', lines 1:16-1:20 *)
Definition core_marker_Copybusiness_logicexample8_intervalsInterval :
  core_marker_Copy example8_intervals_Interval_t := {|
  cloneInst := core_clone_Clonebusiness_logicexample8_intervalsInterval;
|}.

(** [business_logic::example8_intervals::{core::cmp::PartialEq<business_logic::example8_intervals::Interval> for business_logic::example8_intervals::Interval}::eq]:
    Source: 'src/example8_intervals.rs', lines 9:4-12:5 *)
Definition
  example8_intervals_PartialEqbusiness_logicexample8_intervalsIntervalbusiness_logicexample8_intervalsInterval_eq
  (self : example8_intervals_Interval_t)
  (other : example8_intervals_Interval_t) :
  result bool
  :=
  if self.(example8_intervals_Interval_start) s=
    other.(example8_intervals_Interval_start)
  then
    Ok (self.(example8_intervals_Interval_end) s=
      other.(example8_intervals_Interval_end))
  else Ok false
.

(** Trait implementation: [business_logic::example8_intervals::{core::cmp::PartialEq<business_logic::example8_intervals::Interval> for business_logic::example8_intervals::Interval}]
    Source: 'src/example8_intervals.rs', lines 8:0-13:1 *)
Definition
  core_cmp_PartialEqbusiness_logicexample8_intervalsIntervalbusiness_logicexample8_intervalsInterval
  : core_cmp_PartialEq_t example8_intervals_Interval_t
  example8_intervals_Interval_t := {|
  core_cmp_PartialEq_t_eq :=
    example8_intervals_PartialEqbusiness_logicexample8_intervalsIntervalbusiness_logicexample8_intervalsInterval_eq;
|}.

(** Trait implementation: [business_logic::example8_intervals::{core::cmp::Eq for business_logic::example8_intervals::Interval}]
    Source: 'src/example8_intervals.rs', lines 15:0-15:34 *)
Definition core_cmp_Eqbusiness_logicexample8_intervalsInterval : core_cmp_Eq_t
  example8_intervals_Interval_t := {|
  core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst :=
    core_cmp_PartialEqbusiness_logicexample8_intervalsIntervalbusiness_logicexample8_intervalsInterval;
|}.

(** [business_logic::example8_intervals::MergeResultKind]
    Source: 'src/example8_intervals.rs', lines 18:0-21:1 *)
Inductive example8_intervals_MergeResultKind_t :=
| Example8_intervals_MergeResultKind_Disjoint :
  example8_intervals_MergeResultKind_t
| Example8_intervals_MergeResultKind_Merged :
  example8_intervals_MergeResultKind_t
.

(** [business_logic::example8_intervals::{core::clone::Clone for business_logic::example8_intervals::MergeResultKind}::clone]:
    Source: 'src/example8_intervals.rs', lines 17:9-17:14 *)
Definition
  example8_intervals_Clonebusiness_logicexample8_intervalsMergeResultKind_clone
  (self : example8_intervals_MergeResultKind_t) :
  result example8_intervals_MergeResultKind_t
  :=
  Ok self
.

(** Trait implementation: [business_logic::example8_intervals::{core::clone::Clone for business_logic::example8_intervals::MergeResultKind}]
    Source: 'src/example8_intervals.rs', lines 17:9-17:14 *)
Definition core_clone_Clonebusiness_logicexample8_intervalsMergeResultKind :
  core_clone_Clone example8_intervals_MergeResultKind_t := {|
  core_clone_Clone_clone :=
    example8_intervals_Clonebusiness_logicexample8_intervalsMergeResultKind_clone;
|}.

(** Trait implementation: [business_logic::example8_intervals::{core::marker::Copy for business_logic::example8_intervals::MergeResultKind}]
    Source: 'src/example8_intervals.rs', lines 17:16-17:20 *)
Definition core_marker_Copybusiness_logicexample8_intervalsMergeResultKind :
  core_marker_Copy example8_intervals_MergeResultKind_t := {|
  cloneInst := core_clone_Clonebusiness_logicexample8_intervalsMergeResultKind;
|}.

(** [business_logic::example8_intervals::{core::cmp::PartialEq<business_logic::example8_intervals::MergeResultKind> for business_logic::example8_intervals::MergeResultKind}::eq]:
    Source: 'src/example8_intervals.rs', lines 25:4-31:5 *)
Definition
  example8_intervals_PartialEqbusiness_logicexample8_intervalsMergeResultKindbusiness_logicexample8_intervalsMergeResultKind_eq
  (self : example8_intervals_MergeResultKind_t)
  (other : example8_intervals_MergeResultKind_t) :
  result bool
  :=
  match self with
  | Example8_intervals_MergeResultKind_Disjoint =>
    match other with
    | Example8_intervals_MergeResultKind_Disjoint => Ok true
    | Example8_intervals_MergeResultKind_Merged => Ok false
    end
  | Example8_intervals_MergeResultKind_Merged =>
    match other with
    | Example8_intervals_MergeResultKind_Disjoint => Ok false
    | Example8_intervals_MergeResultKind_Merged => Ok true
    end
  end
.

(** Trait implementation: [business_logic::example8_intervals::{core::cmp::PartialEq<business_logic::example8_intervals::MergeResultKind> for business_logic::example8_intervals::MergeResultKind}]
    Source: 'src/example8_intervals.rs', lines 24:0-32:1 *)
Definition
  core_cmp_PartialEqbusiness_logicexample8_intervalsMergeResultKindbusiness_logicexample8_intervalsMergeResultKind
  : core_cmp_PartialEq_t example8_intervals_MergeResultKind_t
  example8_intervals_MergeResultKind_t := {|
  core_cmp_PartialEq_t_eq :=
    example8_intervals_PartialEqbusiness_logicexample8_intervalsMergeResultKindbusiness_logicexample8_intervalsMergeResultKind_eq;
|}.

(** Trait implementation: [business_logic::example8_intervals::{core::cmp::Eq for business_logic::example8_intervals::MergeResultKind}]
    Source: 'src/example8_intervals.rs', lines 34:0-34:41 *)
Definition core_cmp_Eqbusiness_logicexample8_intervalsMergeResultKind :
  core_cmp_Eq_t example8_intervals_MergeResultKind_t := {|
  core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst :=
    core_cmp_PartialEqbusiness_logicexample8_intervalsMergeResultKindbusiness_logicexample8_intervalsMergeResultKind;
|}.

(** [business_logic::example8_intervals::MergeResult]
    Source: 'src/example8_intervals.rs', lines 36:0-40:1 *)
Record example8_intervals_MergeResult_t :=
mkexample8_intervals_MergeResult_t {
  example8_intervals_MergeResult_kind : example8_intervals_MergeResultKind_t;
  example8_intervals_MergeResult_first : example8_intervals_Interval_t;
  example8_intervals_MergeResult_second : example8_intervals_Interval_t;
}
.

(** [business_logic::example8_intervals::merge_intervals]:
    Source: 'src/example8_intervals.rs', lines 42:0-84:1 *)
Definition example8_intervals_merge_intervals
  (a : example8_intervals_Interval_t) (b : example8_intervals_Interval_t) :
  result example8_intervals_MergeResult_t
  :=
  if a.(example8_intervals_Interval_start) s>
    b.(example8_intervals_Interval_start)
  then (
    i <- i32_add b.(example8_intervals_Interval_end) 1%i32;
    if i s< a.(example8_intervals_Interval_start)
    then
      Ok
        {|
          example8_intervals_MergeResult_kind :=
            Example8_intervals_MergeResultKind_Disjoint;
          example8_intervals_MergeResult_first := b;
          example8_intervals_MergeResult_second := a
        |}
    else
      if a.(example8_intervals_Interval_end) s>
        b.(example8_intervals_Interval_end)
      then
        Ok
          {|
            example8_intervals_MergeResult_kind :=
              Example8_intervals_MergeResultKind_Merged;
            example8_intervals_MergeResult_first :=
              {|
                example8_intervals_Interval_start :=
                  b.(example8_intervals_Interval_start);
                example8_intervals_Interval_end :=
                  a.(example8_intervals_Interval_end)
              |};
            example8_intervals_MergeResult_second :=
              {|
                example8_intervals_Interval_start :=
                  b.(example8_intervals_Interval_start);
                example8_intervals_Interval_end :=
                  a.(example8_intervals_Interval_end)
              |}
          |}
      else
        Ok
          {|
            example8_intervals_MergeResult_kind :=
              Example8_intervals_MergeResultKind_Merged;
            example8_intervals_MergeResult_first := b;
            example8_intervals_MergeResult_second := b
          |})
  else (
    i <- i32_add a.(example8_intervals_Interval_end) 1%i32;
    if i s< b.(example8_intervals_Interval_start)
    then
      Ok
        {|
          example8_intervals_MergeResult_kind :=
            Example8_intervals_MergeResultKind_Disjoint;
          example8_intervals_MergeResult_first := a;
          example8_intervals_MergeResult_second := b
        |}
    else
      if b.(example8_intervals_Interval_end) s>
        a.(example8_intervals_Interval_end)
      then
        Ok
          {|
            example8_intervals_MergeResult_kind :=
              Example8_intervals_MergeResultKind_Merged;
            example8_intervals_MergeResult_first :=
              {|
                example8_intervals_Interval_start :=
                  a.(example8_intervals_Interval_start);
                example8_intervals_Interval_end :=
                  b.(example8_intervals_Interval_end)
              |};
            example8_intervals_MergeResult_second :=
              {|
                example8_intervals_Interval_start :=
                  a.(example8_intervals_Interval_start);
                example8_intervals_Interval_end :=
                  b.(example8_intervals_Interval_end)
              |}
          |}
      else
        Ok
          {|
            example8_intervals_MergeResult_kind :=
              Example8_intervals_MergeResultKind_Merged;
            example8_intervals_MergeResult_first := a;
            example8_intervals_MergeResult_second := a
          |})
.

(** [business_logic::example8_intervals::run_example]:
    Source: 'src/example8_intervals.rs', lines 86:0-98:1 *)
Definition example8_intervals_run_example : result unit :=
  r1 <-
    example8_intervals_merge_intervals
      {|
        example8_intervals_Interval_start := 0%i32;
        example8_intervals_Interval_end := 5%i32
      |}
      {|
        example8_intervals_Interval_start := 6%i32;
        example8_intervals_Interval_end := 10%i32
      |};
  b <-
    example8_intervals_PartialEqbusiness_logicexample8_intervalsMergeResultKindbusiness_logicexample8_intervalsMergeResultKind_eq
      r1.(example8_intervals_MergeResult_kind)
      Example8_intervals_MergeResultKind_Merged;
  _ <- massert b;
  _ <-
    massert
      (r1.(example8_intervals_MergeResult_first)
         .(example8_intervals_Interval_start) s= 0%i32);
  _ <-
    massert
      (r1.(example8_intervals_MergeResult_first)
         .(example8_intervals_Interval_end) s= 10%i32);
  r2 <-
    example8_intervals_merge_intervals
      {|
        example8_intervals_Interval_start := 0%i32;
        example8_intervals_Interval_end := 3%i32
      |}
      {|
        example8_intervals_Interval_start := 10%i32;
        example8_intervals_Interval_end := 12%i32
      |};
  b1 <-
    example8_intervals_PartialEqbusiness_logicexample8_intervalsMergeResultKindbusiness_logicexample8_intervalsMergeResultKind_eq
      r2.(example8_intervals_MergeResult_kind)
      Example8_intervals_MergeResultKind_Disjoint;
  massert b1
.

(** [business_logic::example9_pricing::Region]
    Source: 'src/example9_pricing.rs', lines 2:0-6:1 *)
Inductive example9_pricing_Region_t :=
| Example9_pricing_Region_Domestic : example9_pricing_Region_t
| Example9_pricing_Region_Eu : example9_pricing_Region_t
| Example9_pricing_Region_International : example9_pricing_Region_t
.

(** [business_logic::example9_pricing::{core::clone::Clone for business_logic::example9_pricing::Region}::clone]:
    Source: 'src/example9_pricing.rs', lines 1:9-1:14 *)
Definition example9_pricing_Clonebusiness_logicexample9_pricingRegion_clone
  (self : example9_pricing_Region_t) : result example9_pricing_Region_t :=
  Ok self
.

(** Trait implementation: [business_logic::example9_pricing::{core::clone::Clone for business_logic::example9_pricing::Region}]
    Source: 'src/example9_pricing.rs', lines 1:9-1:14 *)
Definition core_clone_Clonebusiness_logicexample9_pricingRegion :
  core_clone_Clone example9_pricing_Region_t := {|
  core_clone_Clone_clone :=
    example9_pricing_Clonebusiness_logicexample9_pricingRegion_clone;
|}.

(** Trait implementation: [business_logic::example9_pricing::{core::marker::Copy for business_logic::example9_pricing::Region}]
    Source: 'src/example9_pricing.rs', lines 1:16-1:20 *)
Definition core_marker_Copybusiness_logicexample9_pricingRegion :
  core_marker_Copy example9_pricing_Region_t := {|
  cloneInst := core_clone_Clonebusiness_logicexample9_pricingRegion;
|}.

(** [business_logic::example9_pricing::{core::cmp::PartialEq<business_logic::example9_pricing::Region> for business_logic::example9_pricing::Region}::eq]:
    Source: 'src/example9_pricing.rs', lines 10:4-17:5 *)
Definition
  example9_pricing_PartialEqbusiness_logicexample9_pricingRegionbusiness_logicexample9_pricingRegion_eq
  (self : example9_pricing_Region_t) (other : example9_pricing_Region_t) :
  result bool
  :=
  match self with
  | Example9_pricing_Region_Domestic =>
    match other with
    | Example9_pricing_Region_Domestic => Ok true
    | Example9_pricing_Region_Eu => Ok false
    | Example9_pricing_Region_International => Ok false
    end
  | Example9_pricing_Region_Eu =>
    match other with
    | Example9_pricing_Region_Domestic => Ok false
    | Example9_pricing_Region_Eu => Ok true
    | Example9_pricing_Region_International => Ok false
    end
  | Example9_pricing_Region_International =>
    match other with
    | Example9_pricing_Region_Domestic => Ok false
    | Example9_pricing_Region_Eu => Ok false
    | Example9_pricing_Region_International => Ok true
    end
  end
.

(** Trait implementation: [business_logic::example9_pricing::{core::cmp::PartialEq<business_logic::example9_pricing::Region> for business_logic::example9_pricing::Region}]
    Source: 'src/example9_pricing.rs', lines 9:0-18:1 *)
Definition
  core_cmp_PartialEqbusiness_logicexample9_pricingRegionbusiness_logicexample9_pricingRegion
  : core_cmp_PartialEq_t example9_pricing_Region_t example9_pricing_Region_t
  := {|
  core_cmp_PartialEq_t_eq :=
    example9_pricing_PartialEqbusiness_logicexample9_pricingRegionbusiness_logicexample9_pricingRegion_eq;
|}.

(** Trait implementation: [business_logic::example9_pricing::{core::cmp::Eq for business_logic::example9_pricing::Region}]
    Source: 'src/example9_pricing.rs', lines 20:0-20:32 *)
Definition core_cmp_Eqbusiness_logicexample9_pricingRegion : core_cmp_Eq_t
  example9_pricing_Region_t := {|
  core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst :=
    core_cmp_PartialEqbusiness_logicexample9_pricingRegionbusiness_logicexample9_pricingRegion;
|}.

(** [business_logic::example9_pricing::Item]
    Source: 'src/example9_pricing.rs', lines 23:0-26:1 *)
Record example9_pricing_Item_t :=
mkexample9_pricing_Item_t {
  example9_pricing_Item_base_price_cents : u64;
  example9_pricing_Item_weight_kg : u32;
}
.

(** [business_logic::example9_pricing::compute_total_price_cents]:
    Source: 'src/example9_pricing.rs', lines 28:0-71:1 *)
Definition example9_pricing_compute_total_price_cents
  (item : example9_pricing_Item_t) (discount_percent : u32)
  (region : example9_pricing_Region_t) :
  result u64
  :=
  if discount_percent s> 100%u32
  then (
    i <- scalar_cast U32 U64 100%u32;
    effective <- u64_sub 100%u64 i;
    i1 <- u64_mul item.(example9_pricing_Item_base_price_cents) effective;
    discounted <- u64_div i1 100%u64;
    match region with
    | Example9_pricing_Region_Domestic =>
      i2 <- u64_mul discounted 10%u64;
      tax <- u64_div i2 100%u64;
      if item.(example9_pricing_Item_weight_kg) s= 0%u32
      then (i3 <- u64_add discounted tax; u64_add i3 0%u64)
      else
        if item.(example9_pricing_Item_weight_kg) s< 1%u32
        then (i3 <- u64_add discounted tax; u64_add i3 500%u64)
        else
          if item.(example9_pricing_Item_weight_kg) s<= 1%u32
          then (i3 <- u64_add discounted tax; u64_add i3 500%u64)
          else
            if item.(example9_pricing_Item_weight_kg) s<= 5%u32
            then (i3 <- u64_add discounted tax; u64_add i3 1000%u64)
            else (i3 <- u64_add discounted tax; u64_add i3 2000%u64)
    | Example9_pricing_Region_Eu =>
      i2 <- u64_mul discounted 20%u64;
      tax <- u64_div i2 100%u64;
      if item.(example9_pricing_Item_weight_kg) s= 0%u32
      then (i3 <- u64_add discounted tax; u64_add i3 0%u64)
      else
        if item.(example9_pricing_Item_weight_kg) s< 1%u32
        then (i3 <- u64_add discounted tax; u64_add i3 500%u64)
        else
          if item.(example9_pricing_Item_weight_kg) s<= 1%u32
          then (i3 <- u64_add discounted tax; u64_add i3 500%u64)
          else
            if item.(example9_pricing_Item_weight_kg) s<= 5%u32
            then (i3 <- u64_add discounted tax; u64_add i3 1000%u64)
            else (i3 <- u64_add discounted tax; u64_add i3 2000%u64)
    | Example9_pricing_Region_International =>
      i2 <- u64_mul discounted 0%u64;
      tax <- u64_div i2 100%u64;
      if item.(example9_pricing_Item_weight_kg) s= 0%u32
      then (i3 <- u64_add discounted tax; u64_add i3 0%u64)
      else
        if item.(example9_pricing_Item_weight_kg) s< 1%u32
        then (i3 <- u64_add discounted tax; u64_add i3 500%u64)
        else
          if item.(example9_pricing_Item_weight_kg) s<= 1%u32
          then (i3 <- u64_add discounted tax; u64_add i3 500%u64)
          else
            if item.(example9_pricing_Item_weight_kg) s<= 5%u32
            then (i3 <- u64_add discounted tax; u64_add i3 1000%u64)
            else (i3 <- u64_add discounted tax; u64_add i3 2000%u64)
    end)
  else (
    i <- scalar_cast U32 U64 discount_percent;
    effective <- u64_sub 100%u64 i;
    i1 <- u64_mul item.(example9_pricing_Item_base_price_cents) effective;
    discounted <- u64_div i1 100%u64;
    match region with
    | Example9_pricing_Region_Domestic =>
      i2 <- u64_mul discounted 10%u64;
      tax <- u64_div i2 100%u64;
      if item.(example9_pricing_Item_weight_kg) s= 0%u32
      then (i3 <- u64_add discounted tax; u64_add i3 0%u64)
      else
        if item.(example9_pricing_Item_weight_kg) s< 1%u32
        then (i3 <- u64_add discounted tax; u64_add i3 500%u64)
        else
          if item.(example9_pricing_Item_weight_kg) s<= 1%u32
          then (i3 <- u64_add discounted tax; u64_add i3 500%u64)
          else
            if item.(example9_pricing_Item_weight_kg) s<= 5%u32
            then (i3 <- u64_add discounted tax; u64_add i3 1000%u64)
            else (i3 <- u64_add discounted tax; u64_add i3 2000%u64)
    | Example9_pricing_Region_Eu =>
      i2 <- u64_mul discounted 20%u64;
      tax <- u64_div i2 100%u64;
      if item.(example9_pricing_Item_weight_kg) s= 0%u32
      then (i3 <- u64_add discounted tax; u64_add i3 0%u64)
      else
        if item.(example9_pricing_Item_weight_kg) s< 1%u32
        then (i3 <- u64_add discounted tax; u64_add i3 500%u64)
        else
          if item.(example9_pricing_Item_weight_kg) s<= 1%u32
          then (i3 <- u64_add discounted tax; u64_add i3 500%u64)
          else
            if item.(example9_pricing_Item_weight_kg) s<= 5%u32
            then (i3 <- u64_add discounted tax; u64_add i3 1000%u64)
            else (i3 <- u64_add discounted tax; u64_add i3 2000%u64)
    | Example9_pricing_Region_International =>
      i2 <- u64_mul discounted 0%u64;
      tax <- u64_div i2 100%u64;
      if item.(example9_pricing_Item_weight_kg) s= 0%u32
      then (i3 <- u64_add discounted tax; u64_add i3 0%u64)
      else
        if item.(example9_pricing_Item_weight_kg) s< 1%u32
        then (i3 <- u64_add discounted tax; u64_add i3 500%u64)
        else
          if item.(example9_pricing_Item_weight_kg) s<= 1%u32
          then (i3 <- u64_add discounted tax; u64_add i3 500%u64)
          else
            if item.(example9_pricing_Item_weight_kg) s<= 5%u32
            then (i3 <- u64_add discounted tax; u64_add i3 1000%u64)
            else (i3 <- u64_add discounted tax; u64_add i3 2000%u64)
    end)
.

(** [business_logic::example9_pricing::run_example]:
    Source: 'src/example9_pricing.rs', lines 73:0-82:1 *)
Definition example9_pricing_run_example : result unit :=
  total <-
    example9_pricing_compute_total_price_cents
      {|
        example9_pricing_Item_base_price_cents := 10000%u64;
        example9_pricing_Item_weight_kg := 2%u32
      |} 10%u32 Example9_pricing_Region_Domestic;
  massert (total s= 10900%u64)
.

(** [business_logic::main]:
    Source: 'src/main.rs', lines 12:0-23:1 *)
Definition main : result unit :=
  _ <- example1_loyalty_run_example;
  _ <- example2_transfer_run_example;
  _ <- example3_inventory_run_example;
  _ <- example4_order_run_example;
  _ <- example5_config_run_example;
  _ <- example6_grading_run_example;
  _ <- example7_moving_average_run_example;
  _ <- example8_intervals_run_example;
  _ <- example9_pricing_run_example;
  example10_retry_run_example
.

End BusinessLogic.
