(** EquivCheck.v Autogenerated by REM-verification **)
Require Import Primitives.
Import Primitives.
Require Import BusinessLogic.
Require Import BusinessLogicRefactored.
Local Open Scope Primitives_scope.


Lemma example10_retry_compute_total_backoff_equiv_check : forall (cfg : example10_retry_RetryConfig_t),
    BusinessLogic.example10_retry_compute_total_backoff cfg = BusinessLogicRefactored.example10_retry_compute_total_backoff cfg.
Proof.
    intros cfg.
    unfold BusinessLogic.example10_retry_compute_total_backoff.
    unfold BusinessLogicRefactored.example10_retry_compute_total_backoff.
    reflexivity.
Qed.
