(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [extract_function_from_trait_with_existing_non_empty_impl_block] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Input.

(** [extract_function_from_trait_with_existing_non_empty_impl_block::Struct]
    Source: 'src/main.rs', lines 1:0-1:19 *)
Definition Struct_t : Type := i32.

(** Trait declaration: [extract_function_from_trait_with_existing_non_empty_impl_block::Trait]
    Source: 'src/main.rs', lines 2:0-4:1 *)
Record Trait_t (Self : Type) := mkTrait_t { Trait_t_bar : Self -> result i32;
}.

Arguments mkTrait_t { _ }.
Arguments Trait_t_bar { _ } _.

(** [extract_function_from_trait_with_existing_non_empty_impl_block::{extract_function_from_trait_with_existing_non_empty_impl_block::Struct}::foo]:
    Source: 'src/main.rs', lines 7:4-7:15 *)
Definition struct_foo : result unit :=
  Ok tt.

(** [extract_function_from_trait_with_existing_non_empty_impl_block::{extract_function_from_trait_with_existing_non_empty_impl_block::Trait for extract_function_from_trait_with_existing_non_empty_impl_block::Struct}::bar]:
    Source: 'src/main.rs', lines 11:4-14:5 *)
Definition
  traitextract_function_from_trait_with_existing_non_empty_impl_blockStruct_bar
  (self : Struct_t) : result i32 :=
  three_squared <- i32_mul 3%i32 3%i32; i32_add self three_squared
.

(** Trait implementation: [extract_function_from_trait_with_existing_non_empty_impl_block::{extract_function_from_trait_with_existing_non_empty_impl_block::Trait for extract_function_from_trait_with_existing_non_empty_impl_block::Struct}]
    Source: 'src/main.rs', lines 10:0-15:1 *)
Definition
  Traitextract_function_from_trait_with_existing_non_empty_impl_blockStruct :
  Trait_t Struct_t := {|
  Trait_t_bar :=
    traitextract_function_from_trait_with_existing_non_empty_impl_blockStruct_bar;
|}.

(** [extract_function_from_trait_with_existing_non_empty_impl_block::main]:
    Source: 'src/main.rs', lines 17:0-19:1 *)
Definition main : result unit :=
  Ok tt.

End Input.
