(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [output] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Out.

(** [output::Struct]
    Source: 'src/main.rs', lines 1:0-1:19 *)
Definition Struct_t : Type := i32.

(** Trait declaration: [output::Trait]
    Source: 'src/main.rs', lines 2:0-4:1 *)
Record Trait_t (Self : Type) := mkTrait_t { Trait_t_bar : Self -> result i32;
}.

Arguments mkTrait_t { _ }.
Arguments Trait_t_bar { _ } _.

(** [output::{output::Struct}::foo]:
    Source: 'src/main.rs', lines 7:4-7:15 *)
Definition struct_foo : result unit :=
  Ok tt.

(** [output::fun_name]:
    Source: 'src/main.rs', lines 17:0-19:1 *)
Definition fun_name : result i32 :=
  i32_mul 3%i32 3%i32.

(** [output::{output::Trait for output::Struct}::bar]:
    Source: 'src/main.rs', lines 11:4-14:5 *)
Definition traitoutputStruct_bar (self : Struct_t) : result i32 :=
  three_squared <- fun_name; i32_add self three_squared
.

(** Trait implementation: [output::{output::Trait for output::Struct}]
    Source: 'src/main.rs', lines 10:0-15:1 *)
Definition TraitoutputStruct : Trait_t Struct_t := {|
  Trait_t_bar := traitoutputStruct_bar;
|}.

(** [output::main]:
    Source: 'src/main.rs', lines 21:0-21:12 *)
Definition main : result unit :=
  Ok tt.

End Out.
