(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [uscore_ret] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module UscoreRet.

(** [uscore_ret::local_inference]:
    Source: 'src/main.rs', lines 1:0-5:1 *)
Definition local_inference : result unit :=
  y <- i32_add 42%i32 1%i32; massert (y s= 43%i32)
.

(** [uscore_ret::main]:
    Source: 'src/main.rs', lines 7:0-9:1 *)
Definition main : result unit :=
  local_inference.

End UscoreRet.
