(** EquivCheck.v Autogenerated by REM-verification **)
Require Import Primitives.
Import Primitives.
Require Import BusinessLogic.
Require Import BusinessLogicRefactored.
Local Open Scope Primitives_scope.


Lemma example5_config_normalise_config_equiv_check : forall (raw : example5_config_RawConfig_t),
    BusinessLogic.example5_config_normalise_config raw = BusinessLogicRefactored.example5_config_normalise_config raw.
Proof.
    intros raw.
    unfold BusinessLogic.example5_config_normalise_config.
    unfold BusinessLogicRefactored.example5_config_normalise_config.
    reflexivity.
Qed.
